### ISSUE TITLE
Is there a way to replace '?' with easy motion?

### ISSUE THREAD

**Issue by wkf** [easymotion/vim-easymotion#108]
Searching forward with ```easymotion-sn``` mapped to '/' works great. Is there a way to work backward? ```easymotion-Fn``` seems allllmost like what I want, but it doesn't always search from the bottom of the document. Essentially I'm looking for ```easymotion-Sn```.

**Comment by haya14busa** [comment]
Sorry for the latttttttte reply.
You can use https://github.com/haya14busa/incsearch-easymotion.vim .
I have no plan to udpate `<Plug>(easymotion-sn>` because it's better to integrate easymotion with incsearch.vim, and it works well with incsearch.vim already.
