### ISSUE TITLE
最後に入力したキーで最初の候補へ移動

### ISSUE THREAD

**Issue by hokorobi** [easymotion/vim-easymotion#116]
EasyMotion_enter_jump_first と同様に Enter でなく、最後に入力したキーで最初の候補へ移動する機能とかどうでしょう？
N ストロークのものには使えないと思いますが、clever-f と同じような操作感で便利かもしれないなと思いました。

思いつき提案ですので、気が向いたら試してみてください。

**Comment by haya14busa** [comment]
とりあえず実装する予定はないので閉じます

**Comment by hokorobi** [comment]
承知の助
