### ISSUE TITLE
Limiting EasyMotion range

### ISSUE THREAD

**Issue by wienerboat** [easymotion/vim-easymotion#121]
Hi!

I use EasyMotion often when I'm writing long documents. As such, I sometimes may have a huge amount of text on my screen at once. Since EasyMotion highlights every possible target on the screen, this means the more there is text on the screen at a given time, the slower EM can operate. This is especially noticeable on my laptop. Basically, even if I only wanted to make a short jump over a dozen words, the operation will be really slow since drawing the the hundreds of unnecessary matches on the screen is a hefty amount of work. This could be addressed by resizing my Vim window, but I feel the total amount of text on the screen shouldn't necessarily hinder Easymotion's ability to perform smaller motions.

So I'm asking if it would be possible to implement some kind of alternative option for EM: limiting EasyMotion's working range to a set number of characters instead of the whole visible buffer. I personally couldn't get started with this, but I'm sure some users who work with large amounts of text would appreciate the safety net and improved snappiness. This wouldn't get in the way when editing code and smaller files, and linewise motions and (EasyMotion's) search could still be used when EasyMotion runs out of range.

Thanks for your work with EM, it's better than ever!

**Comment by TheGrandmother** [comment]
I would love this!
Easy motion works great but I'm currently writing my thesis and i have roughly 2k words in the window at any given time.
And easy-motion can take some time to mark all the words :/
I would love to have the option to only have easy-motion color the next 500 words or 10 lines or something.

Has there been any updates on this feature ?

**Comment by haya14busa** [comment]
How about this?

```vim
function! s:config() abort
  let l = line('.') + 10
  let to = '\%<' . l . 'l'
  return { 'pattern': '\(\<.\|^$\)' . to, 'visualmode': mode(1) is# 'n', 'overwin': 1 }
endfunction

noremap ;w :<C-u>call EasyMotion#go(<SID>config())<CR>
```

**Comment by TheGrandmother** [comment]
that will limit the number of lines searched when jumping to words?
Isn't it better to limit it to the number of words?
I fit about 100 lines on my computer screen and when editing code I don't have that many words per line. So if one where to set the number of words to a limit like ~500 one would still be able to jump around the entire screen when editing code but only withing a of about ~15 lines or so when editing text. And that trade-of might be acceptable.

**Comment by haya14busa** [comment]
I don't have any plan to work on this at least for now. sorry, i'll close it
