### ISSUE TITLE
Including "*.tmp" in wildignore breaks easymotion

### ISSUE THREAD

**Issue by oversearch** [easymotion/vim-easymotion#128]
I have the following line set in my .vimrc:

```
set wildignore=*.tmp,*.swp,*.bak,*.class,*.pyc,*.o,*.exe,*.dll,*.so " ignore some files when auto-completing file names
```

Having *.tmp in that list breaks easymotion on windows, in that executing any easymotion hotkey will just cause the screen to blink once and tell you "No match: <path>".  The path in the error message is to a temporarily file in my windows temp directory.  Removing that entry fixed the problem.

This isn't a huge deal, but it is nice to be able to ignore *.tmp files when I'm auto completing file names.

**Comment by haya14busa** [comment]
it's a bit outdated issue and i couldn't   reproduce it in the first place. close.
