### ISSUE TITLE
Support multi window feature

### ISSUE THREAD

**Issue by haya14busa** [easymotion/vim-easymotion#130]
It's definitely useful for someone including me.

**Comment by haya14busa** [comment]
comming soon...:)

**Comment by eshansingh** [comment]
AWESOME! :+1: I cannot belive how much you Vim plugin authors work. I'm just a lazy Vim user.

**Comment by haya14busa** [comment]
Released! :tada: https://github.com/easymotion/vim-easymotion/releases/tag/v3.0.0

Thank you!
