### ISSUE TITLE
Automatically jump to next match when let g:EasyMotion_enter_jump_first = 1  set

### ISSUE THREAD

**Issue by ghost** [easymotion/vim-easymotion#133]
There should be an option to automatically jump to the next match if let g:EasyMotion_enter_jump_first = 1 is set. 

This way one can directly jump to the next matches by iteratively hitting Enter if it is mapped to `<Plug>(easymotion-next)`.

**Comment by haya14busa** [comment]
I don't have any plan to work on this at least for now. sorry, i'll close it
