### ISSUE TITLE
easymotion doesn't run in OSX terminal since 1.3

### ISSUE THREAD

**Issue by twcamper** [easymotion/vim-easymotion#134]
##### Platform

Snow Leopard, iTerm2 and stock Apple Terminal
##### Issue

"&lt;leader&gt;&lt;leader&gt;f" does not bring up "Search for 1 character:"; it just does nothing.
"&lt;leader&gt;&lt;leader&gt;s" takes me into edit mode (normal VIM behavior, which also indicates EM isn't being run)
- tested with and without my other plugins
- EM 2.0 is working fine in my MacVIM (beautiful job!)
##### bisect

I did a git bisect to narrow it down.  Very soon after 1.3 we get other errors but "Search for 1 character:" keeps working until <code>b368309fb3cb682a909da7cbe1a3026e94aa2511</code>.

<pre>
:~/.vim/janus/vim/tools/easymotion(2.0)$ git bisect start
:~/.vim/janus/vim/tools/easymotion(2.0|BISECTING)$ git bisect bad
:~/.vim/janus/vim/tools/easymotion(2.0|BISECTING)$ git bisect good 1.3
Bisecting: 160 revisions left to test after this (roughly 7 steps)
[65d4d41d66bd6eefee8a49831fefff0054685ab1] Update doc

...

:~/.vim/janus/vim/tools/easymotion(c9d0d18...|BISECTING)$ git bisect good
b368309fb3cb682a909da7cbe1a3026e94aa2511 is the first bad commit
commit b368309fb3cb682a909da7cbe1a3026e94aa2511
Author: haya14busa <hayabusa1419@gmail.com>
Date:   Thu Jan 30 15:31:25 2014 +0900

    Modify to use vital-over for commandline of find motion

    Add buffer completion, paste and mapping feature

:040000 040000 f03bcbfa3aa47056ae3d0c11e28d567e6c2f8060 c00c7d01d3066acc393e6e31a396586e79efe715 M  autoload
:040000 040000 efb4eb9c7ca7ee603df136e96b5cf047efd09633 ee49bebbbaad1b654e56279d59932f9bc7446e77 M  doc
:040000 040000 10ab7347c2e4773f9fdd1354384670b4dfe477b4 b1e1414c63c39e32ba8f227ba3f5525be5ec4e87 M  plugin
</pre>

**Comment by scottchiefbaker** [comment]
Is EasyMotion still not compatible with Vim version 7.2.x? I spend a lot of time on CentOS 6.x and it only supports Vim 7.2. :(

I like @wilywampa's version, but it hasn't been updated in about 9 months.

**Comment by haya14busa** [comment]
I have no plan to support 7.2.
