### ISSUE TITLE
Long lag on first invocation of Easymotion commands 

### ISSUE THREAD

**Issue by jtcwang** [easymotion/vim-easymotion#136]
Hello,

I've noticed that since updating (I last updated 4 months ago), that the first invocation of any easymotion function is slow. When I start a fresh gVim instance, open a file and invoke any easymotion command, gVim will freeze for around 10 seconds.

Is this expected due to Vim's autoload mechanism and new features? Since I did not notice this in previous version of Easymotion.

Environment:
gVim 7.4
Windows 8
Easymotion v2.0

Cheers :)

**Comment by timfeirg** [comment]
I've had something similar, I'm on cfcafd7acb25398731d5be3e2bf8062d57ad0898 and easymotion freezes when invoked, had to kill process to get out, while branch preload doesn't have this problem.

FYI for me this only happens when I'm working on some large code (800+ lines).

**Comment by haya14busa** [comment]
I just updated `preload` branch.
Could you please updating branch and trying it again?

**Comment by timfeirg** [comment]
thanks for the quick response.

* I tried 62b1008014d2c56abaff15a36f8f8885dfca13af on branch preload, and I tried **with or without** the following line in my vimrc:

```
" Preload autload files
call EasyMotion#preload()
```

vim freezes completely on invoking easymotion.

**Comment by haya14busa** [comment]
> I rolled back a couple of commits to discover commit ef0cb2b (a week ago) won't freeze vim.

So, is the bad commit b6861684ce9131b23cd8efdd9f4c5f978cc1ea9a which is the commit after ef0cb2b? 
If b6861684ce9131b23cd8efdd9f4c5f978cc1ea9a is not the bad commit, could you please trying git bisect to detect the bad commit?

I suspect that b11864a4675fedcfb82513eda4ff05103ea08672 is the bad commit bad I cannot reproduce this.

**Comment by timfeirg** [comment]
I'm quite confirmed that b6861684ce9131b23cd8efdd9f4c5f978cc1ea9a was the bad commit

**Comment by haya14busa** [comment]
> FYI for me this only happens when I'm working on some large code (800+ lines).

1. Please give me a example large code.
2. Please tell me the Vim version
3. Please tell me what mappings do you use? `<Plug>(easymotion-s)` or something.
4. Does `freeze` means freeze Vim completely or just it take too long time?
5. If you have some knowledge about Vim script, could you please debugging the code?

**Comment by haya14busa** [comment]
@timfeirg 
There are actually bugs in easymotion and solved it right now. ref: #235
I guess the problem is the same, so could you please updating easymotion and cheking it?

**Comment by timfeirg** [comment]
I was having trouble determining what kind of file will cause the freeze, so it's the folds.
I'm on 2a2cf14bc7d0bee7ac759970b17919d4ed076831 and this problem is gone.
thank you with all my heart, can I buy you guys coffee at bountysource or something?

**Comment by haya14busa** [comment]
> thank you with all my heart, can I buy you guys coffee at bountysource or something?

Thank you very much but I don't use bountysource nor gratipay.
The problem was caused by just my mistake so it's happy enough for me to hear your kindness :)

**Comment by haya14busa** [comment]
I improved first loading time #282. Can you update the plugin and try it again?

**Comment by haya14busa** [comment]
must be fixed
