### ISSUE TITLE
Better Algorithm of making label?

### ISSUE THREAD

**Issue by haya14busa** [easymotion/vim-easymotion#138]
Currently, if `EasyMotion_keys` runs out due to a lot of the number of targets, EasyMotion uses from last to start of `EasyMotion_keys` as a `first` label of combos to type. With this algorithm, EasyMotion can handle a lot of targets with a few key combos.

However, there may be not many targets with basic usage of EasyMotion, so instead of handling many many targets with a few type as much as possible, should it not aims to as few keys as possible, but aims to type label as easy as possible?
#### Config

```
let g:EasyMotion_keys = 'abcde'
```
### Current

Combos to type:

```
a, b, c, da, db, dc, ea, eb, ec, ed, ee, ...
```
### Better?

Config:

```
let g:EasyMotion_first_label = {
\   'display' : '>',
\   'type'    : '<Tab>',
\}
```

Combos to type:

```
a, b, c, d, e, >a, >b, >c, >d, >e, >>a, >>b, >>c, >>d, >>e, >>>a, ....
```

Now, you can know which keys you should type first if there are many targets.

But you have to type `>` many times instead...

**Comment by lisitsyn** [comment]
@haya14busa I drafted some other algorithm of selecting labels that always selects the character on jump position as the first letter of label. The other letter of the label is selected from available keys. I am not yet sure about this idea - would it make sense to issue a PR so we can work it out?

**Comment by haya14busa** [comment]
Sorry to catch up late.

Hm, sounds interesting:sparkles:
Would you mind opening a PR?

**Comment by lisitsyn** [comment]
@haya14busa thanks for your response! Please see PR #212

**Comment by haya14busa** [comment]
I don't have any plan to work on this.
