### ISSUE TITLE
Option for easymotion-sn to not update search register?

### ISSUE THREAD

**Issue by mwgkgk** [easymotion/vim-easymotion#139]
Like vim-smalls default behavior.

**Comment by mydearxym** [comment]
there is another  problem ....
if you search something before , even you set :nohl to unhighlight the instance in current buffer , when you use easymotion to jump to somewhere , the "before hightligh word " will show again , it's pretty annoying ..
[check here](https://gyazo.com/4f8e915b7538314a1d6172578df11ed2)

**Comment by haya14busa** [comment]
Did you set `let g:EasyMotion_add_search_history = 0` ?

**Comment by mydearxym** [comment]
yes  and put it in my .vimrc 
and i tried to set value to 1 , it will highlight where i use Easymotion jump to 

both 0 or 1 will highlight something after jump ..

**Comment by haya14busa** [comment]
I fixed it. Please update easymotion.

**Comment by mydearxym** [comment]
it worked!  amazing work!!

**Comment by haya14busa** [comment]
:)
