### ISSUE TITLE
Colors get mangled after a theme change

### ISSUE THREAD

**Issue by AmaruCoder** [easymotion/vim-easymotion#143]
The new version is awesome. Nevertheless, when there is a theme change, two letter highlighting breaks. See image below.

![easymotion--two letter highlight](https://cloud.githubusercontent.com/assets/2724075/2747757/4f748856-c783-11e3-94ea-da3f7eaa727e.png)

**Comment by haya14busa** [comment]
Please reopen if the problem stil exists.
