### ISSUE TITLE
could you add chinese support?

### ISSUE THREAD

**Issue by jjwt** [easymotion/vim-easymotion#145]
Thank you for the excellent plugin.
In the help, I find that:

```
|Easymotion| can match multibyte Japanese character with alphabetical input.
```

I think,in the same way, chinese should also be supported.
Then after a few day's work, I replace the content of file

```
vim-easymotion/autoload/EasyMotion/migemo/utf8.vim
```

with [here](http://paste.ubuntu.com/7321396/),(I don't know how to upload file here) and put below in my vimrc:

```
let g:EasyMotion_use_migemo = 1
```

and it works!
However, replacing is not a good way, so could you add chinese support 
based on this?

Things may be like this:
1. add a new dirctory named as migemo_chinese
2. add utf8.vim cp936.vim gb18030.vim (for utf8,cp936 and gb18030
   are used often in China)
3. add an option like:
   let g:EasyMotion_use_migemo_chinese = 1

**Comment by haya14busa** [comment]
pull-requests are welcome but I don't have any plan to work on this now.

**Comment by VimWei** [comment]
Is there any update?
