### ISSUE TITLE
Message to indicate search restarting from top

### ISSUE THREAD

**Issue by ayutheos** [easymotion/vim-easymotion#146]
Is there a way to indicate when repeat search (n / N) reached end of file and beginning at  the top? Much like the original vim message "search hit BOTTOM, continuing at TOP".

**Comment by ayutheos** [comment]
Hi, going back to this again...

I've been using incsearch.vim and quite like it. Was wondering if it's possible to use incsearch with easymotion together harmoniously? I very much like the message "search hit BOTTOM, continuing at TOP" in incsearch, and the fast jumping motion of easymotion.

**Comment by haya14busa** [comment]
Could you giving it a shot?
Paste it into your vimrc and press `<Space>` instead of `<Enter>` to execute search.

```vim
augroup incsearch-easymotion
  autocmd!
  autocmd User IncSearchEnter autocmd! incsearch-easymotion-impl
augroup END
augroup incsearch-easymotion-impl
  autocmd!
augroup END

function! IncsearchEasyMotion() abort
  autocmd incsearch-easymotion-impl User IncSearchExecute :silent! call EasyMotion#Search(0, 2, 0)
  return "\<CR>"
endfunction
let g:incsearch_cli_key_mappings = {
\   "\<Space>": {
\       'key': 'IncsearchEasyMotion()',
\       'noremap': 1,
\       'expr': 1
\   }
\ }
```

**Comment by ayutheos** [comment]
Pressing `<Space>` doesn't execute search, it just adds a space to my search term.

My vimrc/gvimrc settings for EasyMotion:

    let g:EasyMotion_re_anywhere = '\v' .
        \       '(<.|^$)' . '|' .
        \       '(.>|^$)' . '|' .
        \       '(\l)\zs(\u)' . '|' .
        \       '(_\zs.)' . '|' .
        \       '(#\zs.)'
    
    hi link EasyMotionTarget        WarningMsg
    hi link EasyMotionShade         WarningMsg
    hi link EasyMotionTarget2First  MatchParen
    hi link EasyMotionTarget2Second MatchParen
    hi link EasyMotionMoveHL Search
    
    " Turn on case sensitive feature
    let g:EasyMotion_smartcase = 1
    
    " keep cursor colum when JK motion
    let g:EasyMotion_startofline = 0 
    
    let g:EasyMotion_grouping = 1
    
    let g:EasyMotion_keys='l,rcpgyf;zqvjwkmasonetuh'
    " default 'asdghklqwertyuiopzxcvbnmfj;'
    
    let g:EasyMotion_do_shade = 0
    let g:EasyMotion_use_upper = 1
    let g:EasyMotion_enter_jump_first = 1
    
    map  /         <Plug>(easymotion-sn)
    omap /         <Plug>(easymotion-tn)
    map  n         <Plug>(easymotion-next)
    map  N         <Plug>(easymotion-prev)
    map  f         <Plug>(easymotion-bd-f)
    map  t         <Plug>(easymotion-bd-t)
    nmap s         <Plug>(easymotion-s2)
    xmap s         <Plug>(easymotion-s2)
    omap z         <Plug>(easymotion-s2)
    map  <Leader>h <Plug>(easymotion-lineforward)
    map  <Leader>j <Plug>(easymotion-j)
    map  <Leader>k <Plug>(easymotion-k)
    map  <Leader>l <Plug>(easymotion-linebackward)

**Comment by haya14busa** [comment]
Please use incsearch.vim's `/`
```vim
map / <Plug>(incsearch-forward)
```

**Comment by haya14busa** [comment]
no response
