### ISSUE TITLE
Enhance `f` to flash numerical labels for later `;` jumps

### ISSUE THREAD

**Issue by joeytwiddle** [easymotion/vim-easymotion#160]
I would like to suggest an alternative to request #133 .

Add a multi-line search on `<Plug>(easymotion-flash-f)` that will immediately go to the first match, but will also **_flash**_ EasyMotion labels for all the other matches on the screen.  (They could disappear on CursorHold event or after 150ms.)  If the user realises they didn't want the first match, they will at least know what keys to press to get to the match they want.  That should be very fast!

In this case, it might feel more Vim-like to use numerical labels.  I am currently using fanfingtastic (multi-line f,t,F,T) so for me a good flow would be:
- `fX` jumps straight to the next 'X' character, but flashes red _numbers_ over all the other 'X's on screen
- Then `5;` would jump to the 5th next match, the one that EasyMotion labelled with a 5.

But you may have your own idea about the keys.  I would accept anything with a small number of keystrokes!

I would be quite happy if matches in the opposite direction were also labelled.  (To feel like ftFT, I would bind a key so these could be reached with `5,`)

The reason I want this is:
- EasyMotion requires extra keystrokes (by default at least).
- It is a little slow on this machine, so I have to wait for the labels to appear!
- And before I perform jump I don't even know if I will need it.  Making that decision requires extra thinking, which I don't have time for!
- For those reasons, I rarely use EasyMotion.  I usually just do a fast immediate jump with `f` or `F`.
- But then sometimes I realise I needed to jump further.  EasyMotion could help me with recommendations of what keys to hit next!

This is a slight re-thinking of EasyMotion, as a hinter during normal Vim usage, rather than something we specifically request.  (But I would only use this for Normal and Visual modes, and keep the other EasyMotion features for operator-pending mode.)

Arguably this feature belongs in one of the f-enhancement plugins, but I am looking at EasyMotion because it already has the complicated code for labelling!

On a related note, here is a little experiment I am trying in flashing/suggesting, as an alternative for (easymotion-j) and (easymotion-k)

```
" Find line easily from Home / Middle / Last keys
nmap <silent> H M:set relativenumber<CR>
nmap <silent> M M:set relativenumber<CR>
nmap <silent> L L:set relativenumber<CR>
autocmd CursorHold * set norelativenumber
```

Is there any bidirectional alternative to (easymotion-j/k)?  It seems I have to decide whether I am going up or down, so I have to think about my cursor position.  It might be nicer if EasyMotion could just label all the lines on screen (starting with those nearby, or near the middle).

**Comment by haya14busa** [comment]
This issue becomes a bit outdated and I don't have any plan to work on this at least for now. sorry, i'll close it
