### ISSUE TITLE
easymotion ignores code-folding

### ISSUE THREAD

**Issue by alexandnpu** [easymotion/vim-easymotion#178]
When folding is used, the column mode does not take the folding line into account.

**Comment by draftman9** [comment]
> Thanks for your advice. I tried that option, and it looks like the following: ![image](https://cloud.githubusercontent.com/assets/1999503/4177966/0d5ae4cc-366b-11e4-8bf0-cfcb8f66c58e.png)
> 
> as you can see, the line indicator does not show at the very beginning of the line and does not have color. Will this be enhanced?
>> It seems highlight for `fold` cannot be overwritten, so it's impossible to fix it. close

For easymotion-jk motion, I have an idea inspired by the semantic checking of some LSP. That is we may place the icon of target like "s" on the the place of "3" which originally is the line number, which can be seen from the quoting picture. I see that the place of line number can be replaced by Error sign and Warning sign and so on. So I think it may also be replaced by the signs of easymotion icons of targets. 

And I think it is appropriate to place the icons of targets on the places of line numbers for the easymotion-jk motion aka line jump motions.
