### ISSUE TITLE
<Plug>(easymotion-next) and <Plug>(easymotion-prev) do not expand folds

### ISSUE THREAD

**Issue by max-baz** [easymotion/vim-easymotion#181]
Consider the following text example. 

```
{cursor}

Folded text {{{
    [destination]
}}}

Another folded text {{{
    [destination]
}}}
```

Collapse all folds.

![image](https://cloud.githubusercontent.com/assets/1177900/4430818/86802e66-4647-11e4-8cf7-7d7d328935b6.png)

Hit &lt;Plug&gt;(easymotion-sn) to enter multichar search, type `destination`, hit Enter.
Cursor remains on the first line, status bar says `EasyMotion: No matches`. 
**I think it is fine.**

![image](https://cloud.githubusercontent.com/assets/1177900/4430822/b6adb590-4647-11e4-9875-026aaa128918.png)

Now hit &lt;Plug&gt;(easymotion-next).
Cursor moves to first `destination`, but fold remains collapsed.

![image](https://cloud.githubusercontent.com/assets/1177900/4430810/278a3db6-4647-11e4-92ee-d7df14f1b404.png)

Expand fold, and you can see that easymotion correctly found `destination`.

![image](https://cloud.githubusercontent.com/assets/1177900/4430812/4ec7ab34-4647-11e4-939c-ca66f6e1fa1d.png)

**I expect fold to be automatically expanded**.

_See how it is done with default vim search._
Hit `/destination<CR>`
Cursor moved to the next `destination`, and its fold was expanded automatically.

![image](https://cloud.githubusercontent.com/assets/1177900/4430830/492a6a30-4648-11e4-8210-743f0f8a7dca.png)

**UPDATE 09/28/2014**

I forgot to mention the main reason why I am proposing to fix this issue in the way I've described :-)
For me, not only search with `/destination<CR>` expand folds, but n / N do the same.
I tried in `vim -u NONE`, so it seems to be the default functionality in vim.

**Comment by eyalk5** [comment]
I don't think it is fine easy-motion says no matches where there are.
