### ISSUE TITLE
Run a command after easymotion finishes

### ISSUE THREAD

**Issue by andreicristianpetcu** [easymotion/vim-easymotion#185]
Is there any way I can run a command after easymotion finishes? I want to run "gf" or "jump to tag". I want to start easymotion and look for words, then jump to the word and automatically run a "gf" on that word. Lots of plugins use gf to go to declarations and maby I can use it shomehow to navigat files also, not only the current file. Thank you for building this plugin! :D

**Comment by louwers** [comment]
In my case, I'd like to `zt` after easymotion finishes, so that the matched line conveniently gets placed on top of the buffer.

**Comment by haya14busa** [comment]
I didn't implement it yet. I guess we can use user autocmd or `inputsave()`/`inputrestore()` functions but I still wonder how this is useful to implement.
EasyMotion cares not only normal mode but also visual and operator-pending mode, so we have to take care the mode difference.

**Comment by haya14busa** [comment]
I don't have any plan to work on this now. close
