### ISSUE TITLE
Very low performance when using s command for navigation

### ISSUE THREAD

**Issue by ThomsonTan** [easymotion/vim-easymotion#193]
Navigation a file with 1000 lines, after type spt to search pattern 'pt', and press a letter key to select, After this, the navigation will take ~5 seconds to complete. Which is really bad to wait so long. The CPU is high and I am not sure it is for recalculating and recovering the syntax highlighting.

**Comment by n1441** [comment]
Turning off `g:EasyMotion_off_screen_search` option significantly improved performance in my case.

**Comment by haya14busa** [comment]
`g:EasyMotion_off_screen_search ` have noting to do with s command.

But by the way, please give me more detail information.
EasyMotion doesn't provide `s` command at the first place. I guess you mean it as `<Plug>(easymotion-s)` or something but please clarify it.

**Comment by haya14busa** [comment]
Please reopen with more detail reproduction steps
