### ISSUE TITLE
Add customizable highlight for easymotion-next/prev

### ISSUE THREAD

**Issue by kevin4fly** [easymotion/vim-easymotion#207]
I have added the following mappings to my vimrc and it works fine.
```vim
nmap ;            <plug>(easymotion-next)
nmap ,            <plug>(easymotion-prev)
```

However, the highlight color is not that suit for me. Here is the default color:
![image](https://cloud.githubusercontent.com/assets/3070033/5876529/de9f0e2e-a352-11e4-85d0-1aebf2c1b5e2.png)

So, could you please add the customizable highlight for it?

**Comment by haya14busa** [comment]
I'm really sorry to reply late.

Please use `EasyMotionMoveHL` as a highlighting group
