### ISSUE TITLE
Different behaviour of easymotion-bd-w in Vim or MacVim

### ISSUE THREAD

**Issue by heinzf** [easymotion/vim-easymotion#214]
Hi,

When calling easymotion-bd-w in MacVim, each word is reachable by 2 or more letters. Easymotion will display two letters, and then allow to refine the selection with a last one if needed.

In Vim however, easymotion only displays a single letter. ![Screenshot](http://i.imgur.com/Unjy8Rq.png)
I'm not sure where to look at to give more relevant information, exception for the :version.

```
diff vimversion.txt macvimversion.txt
4a5,6
> +balloon_eval
> +browse
6a9
> +clientserver
17c20
< +dialog_con
---
> +dialog_con_gui
19a23
> +dnd
29a34
> +fullscreen
40d44
< +lua
49a54
> +mouseshape
52a58
> +odbeditor
75a82,83
> +toolbar
> +transparency
86a95
> +xim
88,91d96
< -balloon_eval
< -browse
< -clientserver
< -dnd
95a101
> -lua
99d104
< -mouseshape
106d110
< -toolbar
108d111
< -xim
```

**Comment by heinzf** [comment]
I tried with with the vim binary used by MacVim, ```/Applications/MacVim.app/Contents/MacOS/Vim```, which contains the same patches according to ```:version``` (1-622).
I have the same problem, the hints are only displayed properly in MacVim.

**Comment by haya14busa** [comment]
I guess the problem is that colors defined with Easymotion doesn't fit with your colorscheme.
What colorscheme do you use?

**Comment by heinzf** [comment]
Thanks!
It was indeed the [color theme](https://github.com/chriskempson/base16-iterm2/blob/master/base16-default.dark.itermcolors), it was one in the base16 collection. I changed it for something else and it's working nicely now.

Question: what makes the emulator colorscheme important to easymotion functionnalities?

**Comment by haya14busa** [comment]
Colorscheme has nothing to do with easymotion functionality.

If you carefully look at your attached image, the target characters are actually replaced with hint characters and colors are also changed slightly.
However, the color doesn't fit with your colorscheme, so it was really hard for you to notice the change.

**Comment by Carpetsmoker** [comment]
I have the same problem. I'm using the *default* colorscheme ... The red letters are okay, but the bright yellow on the white background is not.

Perhaps more sane/safer colours should be chosen? At least something that works with Vim's defaults...

**Comment by heinzf** [comment]
Holly mother of all cows I'm so blind. Thanks, I'll hide in shame for a while.

**Comment by haya14busa** [comment]
I assume the problem was already solved.
As for the changeing default highlight, I'll consider it. Thanks.
