### ISSUE TITLE
Search highlighting reenabled after *n command even with EasyMotion_add_search_history set to zero

### ISSUE THREAD

**Issue by n1441** [easymotion/vim-easymotion#215]
```
set hlsearch
let g:EasyMotion_add_search_history = 0
```
- Found some text using `/`
- Didn't require highlighting; use `:nohlsearch`
- Use `<Plug>(easymotion-sn)`

_EXP_: search history is not updated, highlighting stays turned off
_ACT_: search history is not updated, highlighting is reenabled and shows last search results

**Comment by haya14busa** [comment]
Please write following line in your vimrc
```vim
let g:EasyMotion_move_highlight = 0
```

**Comment by matt-gardner** [comment]
I see the same issue.  I added the line recommended by @haya14busa and I still see the same results.  That line did not fix the issue.

**Comment by haya14busa** [comment]
Oh, I read it worng, sorry.

> Found some text using /
Didn't require highlighting; use :nohlsearch
Use `<Plug>(easymotion-sn)`

> EXP: search history is not updated, highlighting stays turned off

I guess expected behavior is wrong. If you turned of highlight with `:nohlsearch`, and execute search with default Vim command `/`, highlight should be reenabled.

**Comment by matt-gardner** [comment]
Yes, if you execute a search with the default vim command, you expect highlight to be reenabled.  But it seems like the point of setting the option `g:Easymotion_add_search_history = 0` is to _not_ treat the `sn` behavior as a vim search.  I would expect that option to _both_ not add anything to my search history, and not leave anything highlighted that wasn't already highlighted.

**Comment by haya14busa** [comment]
Please use `:h g:EasyMotion_landing_highlight` instead.

`g:Easymotion_add_search_history` doesn't touch highlight at the first place

**Comment by matt-gardner** [comment]
I just tried that, and it doesn't fix the behavior, either.  The previous search term is still highlighted after using a `sn` motion.  I think setting `g:Easymotion_add_search_history = 0` should make the plugin explicitly call `:noh` after performing the motion (or try to save the previous highlight value and restore it, but I'm not sure if that's possible...).

**Comment by haya14busa** [comment]
I tried to reproduce it again, but I cannot. Please reopen if not
