### ISSUE TITLE
Prevent autojump in a single choise case

### ISSUE THREAD

**Issue by WscriChy** [easymotion/vim-easymotion#216]
When there is only one option of a jump, easymotion makes it automatically. I think it is very confusing (because I automatically press <space> or <a> sometimes), it also spoils autorepeat in some cases..
Could you disable it or make an option to disable?

**Comment by haya14busa** [comment]
Thanks for the report. I'll consider to add an option 

> it also spoils autorepeat in some cases

Could you give me a reproduction steps?

**Comment by WscriChy** [comment]
Create a situation when the autojump works, something like when you want to jump to a charecter in vicinity of which there is no anymore such characters. Start recording an action with 'q<register>' then execute recorded action in the area where there are a lot of that characters (that autojumping does not work). The same with repetition: make an action with jump to a character like 'cf<char>' where autojump does not work, try to repeat action with '.' where it suppose. In all that cases there will be a failure.

**Comment by haya14busa** [comment]
I don't have any plan to work on this now.
I think easymotion is not suited for macro (q) in the first place. 

close
