### ISSUE TITLE
More than motion?

### ISSUE THREAD

**Issue by fowlslegs** [easymotion/vim-easymotion#220]
It would be great to use easy motion for more than motion.

Let's say I want to copy the next 13 lines. I would use `V<Leader>jty` because in the general case everything else requires counting or more keystrokes. Why not simply `<Leader>yyt`? Similarly, I want to copy the next 13 words. I would use `v<Leader>eyy`. Instead, this could be `<Leader>yey`.

Repeat the above with `d` instead of `y`.

Repeat the above with `c` instead of `d`.

Yes, I'm that lazy.

**Comment by haya14busa** [comment]
I guess you want this plugin. https://github.com/haya14busa/vim-easyoperator-line

**Comment by haya14busa** [comment]
and this https://github.com/haya14busa/vim-signjk-motion.
