### ISSUE TITLE
Wrong highlighting on easymotion-tln (T, f, F variants too)

### ISSUE THREAD

**Issue by dan-santana** [easymotion/vim-easymotion#222]
When searching with the commands `<Plug>(easymotion-tln)`, `<Plug>(easymotion-Tln)`, `<Plug>(easymotion-fln)` and `<Plug>(easymotion-Fln)`, the characters on other lines are highlighted (when typing).

As these commands only search on the current line, shouldn't it only highlight the matching characters on this line instead of all in the screen?

**Comment by haya14busa** [comment]
> As these commands only search on the current line, shouldn't it only highlight the matching characters on this line instead of all in the screen?

Hm... I agree with you. It should only highlight target range.

**Comment by haya14busa** [comment]
I agreed it should, but I don't have any plan to work on this. It's somewhat difficult to fix it and it's not critical problem.
