### ISSUE TITLE
A smartsign improvement

### ISSUE THREAD

**Issue by DmitryOtroshchenko** [easymotion/vim-easymotion#227]
First of all thank you for maintaining this great plugin!

I use easymotion quite heavily and one of the few issues I have with it are **punctuation signs mistypes**. I use **smartsign** option that helps a lot, however it my opinion optionally replacing all punctuation signs by some wildcard symbol may be beneficial. I would try something like this:

- Create a new option

```
" This symbol will match any symbol from g:EasyMotion_smartsign_wildcard_expand_to
let g:EasyMotion_smartsign_wildcard = '.'
let g:EasyMotion_smartsign_wildcard_expand_to = '!@#$%^&*()--+_=,.<>/?\'"|'
```

- With this example configuration searching (using easymotion) for two symbols `a.` will match: `a.`, `a:`, `a(`, etc. 

- May be even create a global wildcard that matches any symbol

Do you think that this feature is "implementable" and that it will play nice with the other easymotion features?

Thank you.

**Comment by haya14busa** [comment]
Thanks for the request @DmitryOtroshchenko :)
I guess this issue is related with, or same as #135

#135 feature also supports two symbols like `a.` 

It's implementable and useful but I have not merged the feature branch into master for some bug and lack of test.

I'll work on it later as soon as possible. Thanks :+1:

**Comment by DmitryOtroshchenko** [comment]
Thank you for your response. I've taken a look on the tests code and it looks pretty user-friendly. Can I help with testing / writing tests? And btw what was the bug?

**Comment by haya14busa** [comment]
> Can I help with testing / writing tests?

If you want to write tests or test cases, I really appreciate it.

EasyMotion currently use [kana/vim-vspec](https://github.com/kana/vim-vspec) for testing framework but
I use [thinca/vim-themis](https://github.com/thinca/vim-themis) these days for test other my plugins, so
I may write test with vim-themis. I appreciate some test cases ,just using this feature, or some opnion on this :)

Opnion like this https://github.com/Lokaltog/vim-easymotion/issues/135#issuecomment-42261173 or your thought on this feature.


> And btw what was this bug?

Hmm... sorry I forgot the bug detail but as far as I remember, it doesn't handle well with some regular expression.

**Comment by DmitryOtroshchenko** [comment]
I like the configuration template provided in https://github.com/Lokaltog/vim-easymotion/issues/135#issuecomment-42261173. I will try to write some tests for it.

**Comment by haya14busa** [comment]
I'll close this issue because it's almost same as #135.
Please discuss it in #135
