### ISSUE TITLE
fuzzy search?

### ISSUE THREAD

**Issue by ypsun** [easymotion/vim-easymotion#233]
Is it possible to have fuzzy search?
ex. to move to "easymotion", I can type em, emt, ...etc

this is similar to file search behavior supported in [kien/ctrlp.vim](https://github.com/kien/ctrlp.vim).

**Comment by haya14busa** [comment]
Yes, it's possible. I plan to implement fuzzy feature in easymotion or different but similar plugin called incsearch.vim and integrate with easymotion.

**Comment by tomashn** [comment]
@haya14busa :+1: that will be freaking awesome

**Comment by haya14busa** [comment]
Yeah! I implemented fuzzy feature in incsearch.vim and it can be integreate with vim-easymotion :tada: https://github.com/haya14busa/incsearch-easymotion.vim#incremental-fuzzymotion

**Comment by ypsun** [comment]
awesome!!
