### ISSUE TITLE
easymotion-k doesn't work

### ISSUE THREAD

**Issue by naviehuynh** [easymotion/vim-easymotion#234]
Hi,
I use hjkl motion and only -k doesn't work.
When triggering easymotion-k, the red labels appear at the beginning of all lines as expected but they soon just disappear quickly, then I encounter this message: `easymotion invalid target`.

Any idea?
Thanks

**Comment by haya14busa** [comment]
I cannot reproduce this. Please tell me more detail information (like Vim version, commit hash of easymotion, your environment, etc..) and reproduction steps with minimal vimrc.

**Comment by naviehuynh** [comment]
sorry for late reply. Here are some details you requested:

```
OS: Linux mint 17.1
Shell: zsh 5.0.2 (x86_64-pc-linux-gnu)
Vim version: Installed: 2:7.4.052-1ubuntu3 
Easy-motion commit: 2a2cf14bc7d0bee7ac759970b17919d4ed076831 (latest one)
```
My minimal .vimrc
```
    set nocompatible             
    filetype off                  
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    Plugin 'gmarik/Vundle.vim'
    Bundle 'Lokaltog/vim-easymotion'
    let mapleader = " "
    " Vim EasyMotion {
        let g:EasyMotion_do_mapping = 0 " Disable default mappings

        map e <Plug>(easymotion-s2)

        " Turn on case insensitive feature
        let g:EasyMotion_smartcase = 1
        let g:EasyMotion_enter_jump_first = 1

        " JK motions: Line motions
        map <Leader>k <Plug>(easymotion-k) 
        map <C-k> <Plug>(easymotion-k) 
        map <Leader>j <Plug>(easymotion-j)
        map <Leader>l <Plug>(easymotion-lineforward)
        map <Leader>h <Plug>(easymotion-linebackward)
    " }
    call vundle#end()            " required
    filetype plugin indent on    " required

```

**Comment by haya14busa** [comment]
I cannot reproduce this with your vimrc.
Could you please updating easymotion and trying it again?
If the problem persists, please give me reproduction steps in addition to vimrc.

**Comment by naviehuynh** [comment]
The above commit is already the latest in master branch.
This is strange, I tried compiling vim from source and still get the same error with that vimrc. Is there any code I can insert into my easymotion script to make debugging easier?

**Comment by haya14busa** [comment]
Firstly, could you please putting `:echom char` below this line https://github.com/easymotion/vim-easymotion/blob/2a2cf14bc7d0bee7ac759970b17919d4ed076831/autoload/EasyMotion.vim#L1122 ?

I guess you can see the character which unexpectedly input with `:message`

**Comment by naviehuynh** [comment]
Yeah, I got this:
```EasyMotion: Vim(let):E716: Key not present in Dictionary: : function EasyMotion#JK..<SNR>75_EasyMotion..<SNR>75_PromptUser, line 213```

**Comment by haya14busa** [comment]
Can you give me more detail reproduction steps?

For example,

#### test.txt
```
vim
vim
vim
```

### How to reproduce
1. `vim test.txt`
2. `3gg`
3. `<Leader>k`

**Comment by naviehuynh** [comment]
yeah it is exactly as simple as the example you suggested above.
```echom char``` prints out an empty line.

**Comment by haya14busa** [comment]
Could you please mapping `<Plug>(easymotion-k)` to another key like below and trying again?

`:map <Leader><Space> <Plug>(easymotion-k)`

**Comment by naviehuynh** [comment]
same error, I also tried leaving my leader key as vim default and some other combination (C-k), same thing.

**Comment by haya14busa** [comment]
Can you try with this config? (There is space)

```vim
let g:EasyMotion_keys = ' abcdefghijklmnopqrstuvwxyz'
```

**Comment by naviehuynh** [comment]
yeah I jumps to the first line above my current line, I guess it's the space char being inserted somehow.

**Comment by naviehuynh** [comment]
if I type the command to map the key when I am in an opened buffer, it works.

**Comment by haya14busa** [comment]
I assume tthe problem is, there is a trailing white spaces in `<Plug>(easymotion-k>` line.
Please remove the trailing white space.

**Comment by naviehuynh** [comment]
@haya14busa you are right lol, cant believe I didn't spot this for months :+1:

**Comment by haya14busa** [comment]
:)

**Comment by losemyheaven** [comment]
I met the same problem.
Fortunately, I fixed it after this issue!
Thanks!!!!

**Comment by iliis** [comment]
Setting `set listchars=trail:¬` in your vimrc helps with these kinds of issues. It will highlight any trailing whitespace. It might also drive you nuts when editing files from other people... ;)
