### ISSUE TITLE
Search when folding hangs Vim

### ISSUE THREAD

**Issue by yusiwen** [easymotion/vim-easymotion#235]
Thanks for your great work, I really love the functionalities provided by this plugin.

When I'm using it, I'v found that when I hit '/' to search a pattern in a file which has folds, Vim got hanged, frozen totally with 100% CPU usage.

For example, my .vimrc file has multiple folds like:
```text
" Vundle {{{
   ...
   Plugin '....'
   Plugin '....'
" }}}

" General settings {{{
   set xx = yy
   ...
" }}}
```
When these folds are folded, search with '/' will hang Vim immediately when I hit Enter. But when these folds are opened, search works just fine. 

I've tried removing all the plugins except `vundle` and `vim-easymotion`, and all the settings except `vim-easymotion` and folding, but unfortunately the problem is still there. So there shouldn't be any plugin conflicts.

My easymotion setting is:
```text
  ... vundle setting ommitted

  set foldmethod=marker
  set foldcolumn=1

  let g:EasyMotion_do_mapping = 0 " Disable default mappings
  map  n <Plug>(easymotion-next)
  map  N <Plug>(easymotion-prev)
  let g:EasyMotion_smartcase = 1
  let g:EasyMotion_startofline = 0 " keep cursor colum when JK motion
```

**Comment by haya14busa** [comment]
Thank you for the report @yusiwen !
I fixed it right now:)
Please reopen if the problem is not solved.

**Comment by yusiwen** [comment]
Thanks. The problem is gone after applying your patch. 

BTW, I'm just curious, how to debug vim scripts when such problem causing vim freezed? Is there any tools?

**Comment by haya14busa** [comment]
Hm... I just can know the source code so I could debug it but I didn't use any specific tools.
If the `:profile` can use for this, I guess it helps.

This is just a print debug, but below function can use like logging function and you can view the output from outside of vim.

```vim
function! Plog(msg) "{{{
  try
    call vimproc#system('echo "' . strtrans(PP(a:msg)) . '" >> ~/vim.log')
  catch
    call vimproc#system("echo '" . strtrans(a:msg) . "' >> ~/vim.log")
  endtry
  " call Plog('called')
  " tail -f ~/vim.log
endfunction "}}}
````

NOTE: it depends on [Shougo/vimproc.vim](https://github.com/Shougo/vimproc.vim)

**Comment by yusiwen** [comment]
OK, I got it. Thanks. :+1:
