### ISSUE TITLE
Make * to use the Easy motion

### ISSUE THREAD

**Issue by Mariappan** [easymotion/vim-easymotion#236]
Hi 

I have the following mapping in my vimrc to completlely replace the vim in-built search.
```vim
map , <Plug>(easymotion-prefix)

" Use 's' to search in current page
map s  <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)

map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)
```
But I have a problem with * though, since it uses the vim default search. I am not able to move to next hit using n or N since i already remapped n and N to easymotion-next & prev.

Is there a way to map * also to use easy motion search ??

**Comment by haya14busa** [comment]
Sorry for the late response.

It's possible to provide `*` in easymotion for the search history, but there is more search focused plugin called incsearch.vim. You can integrate it with easymotion using this plugin https://github.com/haya14busa/incsearch-easymotion.vim 
I think most of behavior is compatible with easymotion's one. Can you give it a shot?

**Comment by haya14busa** [comment]
https://github.com/haya14busa/incsearch-easymotion.vim  should works `*` fine. Please reopen if not.
