### ISSUE TITLE
first use of vim-easymotion very slow in neovim

### ISSUE THREAD

**Issue by jsholmes** [easymotion/vim-easymotion#242]
I have these options set:

``` vim
" =============== vim-easymotion   ==========
let g:easymotion_leader_key = '\'
nmap s <Plug>(easymotion-s2)
nmap / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
" Gif config
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)

let g:EasyMotion_startofline = 0 " keep cursor colum when JK motion
let g:EasyMotion_smartcase = 1   " be a bit zalier about what to target
let g:EasyMotion_do_shade = 1
let g:EasyMotion_inc_highlight = 1
let g:EasyMotion_move_highlight = 1
let g:EasyMotion_landing_highlight = 1
" ===========================================
```

When I first open a new neovim window and hit, for instance, '/', nvim freezes for ~3 seconds before the font dims and I start searching.

This does not happen in macvim, fwiw.

The next time I do this in the same buffer or a newly opened one, it's fine.

**Comment by sanwv** [comment]
me too

**Comment by mikekreeki** [comment]
Confirming the issue.

**Comment by haya14busa** [comment]
Sorry for the late response.
Could you run profiling? See `:h profile`

**Comment by haya14busa** [comment]
I improved first loading time #282. Can you update the plugin and try it again?

**Comment by diefans** [comment]
For neovim/mac/iterm2 I can confirm dramatic improvements of loading time and first-use-time-of-easymotion. Thanks man!

**Comment by haya14busa** [comment]
Thanks!
