### ISSUE TITLE
How can I install vim-easymotion manually?

### ISSUE THREAD

**Issue by libo26** [easymotion/vim-easymotion#244]
One of my develop machine is not able to connect to the Internet, so I have to install vim-easymotion manually. I copied all files into my .vim directory, word motion worked fine. However, when using f motion, "vital: version file not found: easymotion" occurred.

**Comment by haya14busa** [comment]
Sorry for the late response.

I guess you didn't copy all files. Please try again and if you find the same error,  please paste the `tree` command output in your .vim directory.
