### ISSUE TITLE
Highlight possible targets when creating a count

### ISSUE THREAD

**Issue by joeytwiddle** [easymotion/vim-easymotion#245]
Sometimes I do `c6w` only to realise that I mis-counted, and must now `u` and do `c7w`.  Therefore I propose:

When the user is in "count" state of Normal mode (let's say they have typed `24` or `c24`), I would like display or flash up a few highlights over the text:
- A 'l' 24 characters to the right of the cursor
- A 'h' 24 characters to the left of the cursor
- A 'j' 24 lines below the cursor
- ...
- A `W` 24 words to the right of the cursor
- A `n` at the 24th next search result
- A `;` at the 24 next `f` result

That way the user will know if they guessed the number correctly, before committing to the action.

**Comment by haya14busa** [comment]
vim-easymotion aims to help user to use motion without such a troublesome counting.
So, you should use `<Plug>(easymotion-w)` in the first place.

If you want to highlight targrts, you can implement it without easymotion.
I guess you should create such plugin on your own
