### ISSUE TITLE
jumptoanywhere colors

### ISSUE THREAD

**Issue by kaatish** [easymotion/vim-easymotion#247]
The colors for jumptoanywhere are a bit confusing, or at least they are for my colorscheme. Both the letters for a position are of the same color and when such pairs are right next to each other, it is unclear as to which letter is the first. Perhaps, this is not a good explanation of the issue, so I have attached a screenshot.

![easymotion](https://cloud.githubusercontent.com/assets/2610638/10053915/8c712484-61fc-11e5-8cd6-4c5cab286408.jpg)

Is it possible to change the colors of the highlighted letters ourselves?

**Comment by haya14busa** [comment]
Sorry for the late reply.
Please see `:h easymotion-custom-hl`. You can customize highlight. Thanks.

**Comment by mb720** [comment]
Putting this in my `.vimrc` worked great for me:

    hi EasyMotionTarget2First cterm=bold ctermbg=none ctermfg=red
    hi EasyMotionTarget2Second ctermbg=none ctermfg=red
