### ISSUE TITLE
easymotion-repeat

### ISSUE THREAD

**Issue by rosshadden** [easymotion/vim-easymotion#248]
`easymotion-repeat` doesn't do what the docs say for me.

If I say `d<plug>(easymotion-j)k` (where `k` is some random target letter), attempting to repeat this motion with `d<plug>(easymotion-repeat)` instead brings up the target list again, causing me to have to hit the `k` target again.

**Comment by WscriChy** [comment]
>Repeat last motion type including input target character.

That means it repeats **target character** (for 1 char jump (f, F, t, T), but not motion character).

**Comment by rosshadden** [comment]
Oh, okay.  Maybe I can make my own function/mapping that does what I was wanting.

Thanks!

**Comment by haya14busa** [comment]
I'm sorry for the late response. Please just type dot with installing vim-repeat. see https://github.com/easymotion/vim-easymotion#support-for-dot-repeat

**Comment by haya14busa** [comment]
On second thought, the document for `<Plug>(easymotion-repeat)` isn't clear.

`input target character` doesn't mean random target letter, but it means input character(s) for find-motion like `<Plug>(easymotion-f)`. So, `<Plug>(easymotion-repeat)` is not related with `<Plug>(easymotion-j)`.
