### ISSUE TITLE
Use of easymotion-prefix and easymotion-sn

### ISSUE THREAD

**Issue by PhML** [easymotion/vim-easymotion#249]
There is something I don't understand about the configuration. Here is mine:

```vimL
let g:mapleader = ","
map - <Plug>(easymotion-prefix)
nmap <Leader>S <Plug>(easymotion-sn)
```

*easymotion-s* is mapped to `-s` as expected, but *easymotion-sn* is mapped to `,S` while I want it to be mapped to `-S`. Is it a bug or something I am missing ?

**Comment by eshansingh** [comment]
Because you explicitly mentioned `<leader>`, Vim is just using your leader. Use:

```
nmap -S <Plug>(easymotion-sn)
```

**Comment by haya14busa** [comment]
`<Plug>(easymotion-prefix)` and `<Leader>` is not the same things. @eshansingh's solution should work fine, so i closed this issue.
