### ISSUE TITLE
Idea: Jump to a character in two presses (best case)

### ISSUE THREAD

**Issue by vim-nyan-cat** [easymotion/vim-easymotion#250]
Thanks for continuing to develop and maintain EasyMotion @haya14busa!

I've been using ```nmap s <Plug>(easymotion-s)``` to jump to a character in three presses (best case) with good results. I was thinking of ways to make jumping to a character even more efficient and came up with this rough idea:
```VimL
" holding the w key activates EasyMotion to jump to the letter w on release

function! PressOrRelease()
    let g:_reltime = reltime()
    nnoremap w <Nop>
    augroup press_or_release
        autocmd!
        autocmd CursorHold *
            \ execute 'autocmd! press_or_release' |
            \ let &updatetime = g:_updatetime |
            \ if (reltime(g:_reltime)[0] == 0) && ((reltime(g:_reltime)[1] / 1000) < 40) |
                \ call feedkeys('w', 'n') |
            \ else |
                \ call feedkeys("\<Plug>(easymotion-s)w") |
            \ endif |
            \ execute 'nnoremap <silent> w :<C-u>call PressOrRelease()<CR>'
    augroup END
    let g:_updatetime = &updatetime
    set updatetime=30
endfunction

nnoremap <silent> w :<C-U>call PressOrRelease()<CR>
```
I'm not sure if this can be generalized to work with all keys.

**Comment by haya14busa** [comment]
The idea itself might be fine, but it doesn't work well with Vim's archtecture, I guess.
We need to manipulate updatetime which is for `CursorHold` variable not for timer.
Vim doesn't support onkeydown and onkeyup event too.
I tried your code but the behavior is not stable, so it's hard to support it by default.

**Comment by vim-nyan-cat** [comment]
Okay, thanks for considering it. I'll close the issue.
