### ISSUE TITLE
Can I just press <cr> on Target Key prompt?

### ISSUE THREAD

**Issue by poldie** [easymotion/vim-easymotion#252]
When I search, then press tab a number of times to navigate to pages containing the search term, I sometimes find the page I'm looking for, but if you then press escape or enter you abort the search and return to the location you started from.  I suppose I could press one of the target keys but is it presently possible to customise my config so that enter leaves me on the current page? Failing that, perhaps it could be added as a feature/option?

**Comment by haya14busa** [comment]
Sorry for the late reply.
Please use `:h g:EasyMotion_enter_jump_first`
