### ISSUE TITLE
paste (command+v) is broken in easymotion

### ISSUE THREAD

**Issue by kelly-apollo** [easymotion/vim-easymotion#253]
After `map  / <Plug>(easymotion-sn)` mapping and type `/` to prompt searching, hit `command+v` and it will paste text `"+gP` instead of text in clipboard, do I miss something?

**Comment by haya14busa** [comment]
Can you try `:EMCommandLineNoreMap "+gP <C-r>+`?

**Comment by kelly-apollo** [comment]
It works! But my working command is `:EMCommandLineNoreMap \"\+gP <C-r>+`.
Thanks @haya14busa !
