### ISSUE TITLE
Fails to repeat last action

### ISSUE THREAD

**Issue by WscriChy** [easymotion/vim-easymotion#254]
I press `d<easymotion-f>(<some jump char>`  
And I have an auto-save function

```
au CursorHold,InsertLeave * write
```

That is triggered somewhere after the action. Then I press `.` and I have that EasyMotion is Cancelled.

**Comment by haya14busa** [comment]
`d<easymotion-f>(<some jump char>` is not related with CursorHold nore InsertLeave, and I cannot reproduce it.
