### ISSUE TITLE
Repeting action with dot corrupts file modified state

### ISSUE THREAD

**Issue by WscriChy** [easymotion/vim-easymotion#255]
I do `d<easymotion-f>(<some jump char>`, then I press `.u` and file is not modify. I can close the vim, it wont ask me if the file should be saved. Then when I open the file I do not have my first modification with `d<easymotion-f>(<some jump char>. You can repeat dot many times without saving a file and then press`u`many times as well and all the time the content of the buffer will be changed but`modified`option of the buffer will be in`nomodified` state.

**Comment by haya14busa** [comment]
Can you give me a easy reproduction steps with expected and actual behavior?
I cannot reproduce it.
