### ISSUE TITLE
\C to enforce case sensitivity in search patterns doesn't work

### ISSUE THREAD

**Issue by eshansingh** [easymotion/vim-easymotion#256]
At first I was skeptical about `<Plug>(easymotion-sn)`, but I liked it and I mapped `/` to trigger it instead of normal search. It even supports regex, which I didn't expect. But there's one bug I'm facing.

As an example, I'll use this section of my `~/.vimrc`:

![Vimrc section](http://i.imgur.com/auw02wX.png)

In this case, `ignorecase` is on and `smartcase` is off. Now let's search for `<Leader>` (notice capital L):

![Search for <Leader>, ignorecase on](http://i.imgur.com/OqJ6vqP.png)

As expected, it matches `<leader>` too. Now let's try `<Leader>\C`. `\C` enforces case sensitivity.

![Case sensitive](http://i.imgur.com/vaDB3ao.png)

Nope, still matches `<leader>` with a small 'l'.

However, `:set noignorecase` and then searching works (i.e returns no matches), rather obviously, but the whole point of the `\c` (ignore case) and `\C` (don't ignore case) modifiers is so that they do that regardless of `ignorecase` or `smartcase`.

And normal search with this works fine (after `:unmap /`):

![Pattern not found](http://i.imgur.com/yMA05ly.png)

First section of `mvim --version`:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 21 2015 18:18:32)
MacOS X (unix) version
Included patches: 1-769
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_binary
+arabic          +find_in_path    -mouse_sysmouse  +tag_old_static
+autocmd         +float           +mouse_urxvt     -tag_any_white
+balloon_eval    +folding         +mouse_xterm     +tcl
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+cindent         -gettext         +netbeans_intg   +title
+clientserver    -hangul_input    +odbeditor       +toolbar
+clipboard       +iconv           +path_extra      +transparency
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
+farsi           +mouse_netterm   +syntax
```

**Comment by eshansingh** [comment]
@haya14busa Anything on this yet?

**Comment by haya14busa** [comment]
I confirmed issue.
I'm sorry but I created https://github.com/haya14busa/incsearch-easymotion.vim before and it's more compatible with Vim's default search and you can almost all things which `<Plug>(easymotion-sn)`. does.
So, I don't have big motivation to fix `<Plug>(easymotion-sn)` which incsearch-easymotion.vim  already solves. 
Can you try incsearch-easymotion.vim?

**Comment by eshansingh** [comment]
Yeah, it works pretty well for my purposes. Thanks!
