### ISSUE TITLE
Remapping of prefix key isn't working for me. 

### ISSUE THREAD

**Issue by still-learning** [easymotion/vim-easymotion#258]
nnoremap - \<Plug>(easymotion-prefix)

typing: \\\\w
brings up easy motion, but

typing: -w
or: --w
doesn't do anything

I've tried a variety of things while also checking the read-me, docs, and github issues. What am I doing wrong?

**Comment by eshansingh** [comment]
It would be a little more helpful if you described the `variety of things` that you tried, and what their results were.

**Comment by haya14busa** [comment]
Please use `map` instead of `nnoremap`.
