### ISSUE TITLE
Searched string stays highlighted

### ISSUE THREAD

**Issue by sittim** [easymotion/vim-easymotion#260]
Executing search `/mystring`, then hitting `<CR>` then choosing a selection, keeps all of the found searched strings highlighted in all windows, no matter what I do, till I search for another string and hit `<CR>`.  Sometimes it is really annoying, is there a way to clear the highlights?

**Comment by eshansingh** [comment]
`:nohlsearch` will make all of them go poof.
You can make a mapping like I have done. Put this in your `~/.vimrc`:
```
nnoremap <leader>nh :nohlsearch<CR>
````
If you haven't set the `mapleader` setting (see `:h mapreader`) then `\nh` will execute `:nohlsearch`.

**Comment by sittim** [comment]
Works awesome, thank you, I must have missed the command scanning through manual....

**Comment by eshansingh** [comment]
By the way, this command isn't a easymotion thing, it's vim built-in. You can go to `:h /` for a pretty good rundown of searches and search commands.
