### ISSUE TITLE
Create a way to change the green color when searching.

### ISSUE THREAD

**Issue by kori** [easymotion/vim-easymotion#261]
Unless I'm misunderstanding, there's no way to do this.

In the readme, there's this:

`hi EasyMotionMoveHL ctermbg=green ctermfg=black`

This doesn't seem to do anything... At least here.

Is there a way to do this?

**Comment by haya14busa** [comment]
Please see `:h g:EasyMotion_move_highlight`.
And I cannot reproduce it. `:hi EasyMotionMoveHL` works in my environment.

**Comment by ri-aje** [comment]
hi, I think I ran into the same issue. basically I only use `easymotion-sn`. in there, after I invoke the functionality and start typing but before finally settling down on any target by pressing the enter key, easymotion will highlight matches incrementally, but the highlighting color is always green, which is not very visible in a light color theme that I use.

I tried modifying `EasyMotionMoveHL` to various colors but I don't see any difference for the green matches. I also tried setting `g:EasyMotion_move_highlight` to 0 and 1, and played with all the combinations with `EasyMotionMoveHL`, and that doesn't seem to bring any difference either.

I read the docs and `g:EasyMotion_move_highlight` seems to be controlling `easymotion-next/prev` which is not what I use. can you give it a try see if you can repro it? thanks.

**Comment by haya14busa** [comment]
Please use EasyMotionIncCursor instead
