### ISSUE TITLE
Cannot remap <C-l> using EMCommandLineNoreMap

### ISSUE THREAD

**Issue by phongvcao** [easymotion/vim-easymotion#262]
Hi,

I am trying to remap `<C-l>` to `<C-f>` or `<Right>` in `vim-easymotion`'s command-line mode but it doesn't work. Here is what I have in my `.vimrc`:

```vim
    autocmd VimEnter,BufEnter * :EMCommandLineNoreMap <C-l> <Right>
    autocmd VimEnter,BufEnter * :EMCommandLineNoreMap <C-l> <C-f>
```

However, after having these keymappings, `<C-l>` still behaves as `<Over>(buffer-complete)` instead of moving cursor to the right in command-line (search) mode. What did I do wrong here?

**Comment by haya14busa** [comment]
I'm sorry for the late reply. I fixed this issue. Thank you for the report! :+1:
