### ISSUE TITLE
Disabling easy motion in the current session?

### ISSUE THREAD

**Issue by gerroon** [easymotion/vim-easymotion#263]
Hi

Is it possible to disable easymotion inside a running vim session? I can not locate info about it.

Thanks

**Comment by haya14busa** [comment]
You cannot do it. You can remove easymotion from runtimepath by using plugin manager's feature like `:NeoBundleDisable` https://github.com/Shougo/neobundle.vim
Or you can manually `:unmap` your defined keys.
