### ISSUE TITLE
Note about regexes for w, b, W, B, e, and E

### ISSUE THREAD

**Issue by YggdrasiI** [easymotion/vim-easymotion#267]
Hello,

as I'm interested in regexes for common VIM motions I compared the regexes of your plugin with the 
motions of VIM and found a few differences. It would be comprehensible if you decide not to match to 100% with
the normal jumpmarks for practical reasons, but here are my regex-suggetions for a better (100%?! I found no differences) matching.

Note that the searchpos()-functions respects \zs. (Setting the /-register to one of the regexes made the analysis easier.)

``` w/b 
your current regex: '\(\<.\|^$\)'
this respects the 'not \k'-transitions: '\<\|^\S\|\s\zs\S\|\>\zs\S\|^$\|\%$'  
```

```  W/B
your current regex: '\(\(^\|\s\)\@<=\S\|^$\)'
regex without(?) lookback: '\(\(^\|\s\)\zs\S\|^$\)'
```
Edit: W also requires document end ('\%$') as match.

``` ge
your current regex: '\(.\>\|^$\)'
same effect like new w/b-regex '.\ze\>\|\S\ze\s*$\|\S\ze\s\|\k\zs\>\S\ze\|\S\<\|^$\|\%^'
```

e shows the strange(?) behaviour that it does not stop on empty lines. Tiny difference to 'ge'.
``` e
your current regex: '\(.\>\|^$\)'
same effect like new w/b-regex '.\ze\>\|\S\ze\s*$\|\S\ze\s\|\k\zs\>\S\ze\|\S\<'
```

gE/E shows the same difference on newlines.
Edit: For a 100% matching, the beginning of the document is also required
```
gE '\(\S\(\s\|$\)\|^$\|\%^\)'

Regards YggdrasiI

**Comment by haya14busa** [comment]
First, thank you for the interesting report! :+1:

As for the w/b/e/ge motions, there are iskeyword compatible motions like `<Plug>(easymotion-iskeyword-w)` which doesn't match the EOF though.

I didn't make it as default because it matches lots positions compared to old incorrect motions like `<Plug>(easymotion-w)` and this change will annoy some users in my opinion.

I want to include your correct regex to `iskeyword` compatible motions. (I didn't implement large WORD motions though ...)

Can you make a PR?

**Comment by YggdrasiI** [comment]
Not to use it as default motion seems absolutely legit for me. 
It was a good idea from you to  note the iskeyword-functions. Seems that I'm overlooked them.

Yes, I can make a PR, but it will take a few days...
I will try to extend your test suite with an test for the iskeyword-movements, too.
With a test it should be easier to decide if it its worth to switch to a more complex regex.

**Comment by haya14busa** [comment]
Thanks.  Tests will really help me a lot :+1:
The time is no problem, please take your time

**Comment by YggdrasiI** [comment]
Pulled my changes now [here](https://github.com/easymotion/vim-easymotion/pull/276).
