### ISSUE TITLE
Error the first time using easymotion-overwin-w

### ISSUE THREAD

**Issue by cwbriscoe** [easymotion/vim-easymotion#268]
The first time using easymotion-overwin-w, I get an undefined variable error.  If I use another function first, such as easymotion-overwin-f2, then it will work.  I am using neovim if that matters.  Here is the error text:

```
Error detected while processing function EasyMotion#overwin#w..EasyMotion#overwin#move:                                                                                                       
line    1:                                                                                                                                                                                    
E121: Undefined variable: g:EasyMotion_hl_group_shade                                                                                                                                         
E116: Invalid arguments for function <SNR>81_move                                                                                                                                             
E15: Invalid expression: s:HitAHintMotion.move(a:pattern, {   'keys': g:EasyMotion_keys,   'use_upper': g:EasyMotion_use_upper,   'highlight': {     'shade': g:EasyMotion_hl_group_shade,    
 'target': g:EasyMotion_hl_group_target,   },   'jump_first_target_keys':     (g:EasyMotion_enter_jump_first ? ["\<CR>"] : []) +     (g:EasyMotion_space_jump_first ? ["\<Space>"] : []),   'd
o_shade': g:EasyMotion_do_shade, })
```

    My config:
    " Easymotion settings
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_smartcase=1
    let g:EasyMotion_startofline = 0 
    nmap s <Plug>(easymotion-overwin-f2)
    nmap w <Plug>(easymotion-overwin-w) 
    map <Leader>l <Plug>(easymotion-lineforward)
    map <Leader>j <Plug>(easymotion-j)
    map <Leader>k <Plug>(easymotion-k)
    map <Leader>h <Plug>(easymotion-linebackward)

**Comment by haya14busa** [comment]
Thank you for the report, I fixed it.

**Comment by talia523** [comment]
Why am I encountering the same issue where easymotion-overwin-line and easymotion-overwin-w only become effective after executing easymotion-overwin-f2? Otherwise, they also result in errors. My environment is Vim 9.1 with EasyMotion 3.0.1.
![image](https://github.com/user-attachments/assets/6f573788-c59f-4d7f-b83a-04dc0cac962d)
