### ISSUE TITLE
Double cursor in Neovim's cmdline

### ISSUE THREAD

**Issue by ichbean** [easymotion/vim-easymotion#269]
In Neovim, while searching with EasyMotion, there are two cursors: VitalOverCommandLineCursor (magenta coloured) and "real" cursor. 

![dcursor](https://cloud.githubusercontent.com/assets/16004620/12599813/9903f218-c49d-11e5-812e-1d18fb4c4387.png)

Is there a way to disable VitalOverCommandLineCursor in Neovim?

**Comment by haya14busa** [comment]
This issue is same as https://github.com/haya14busa/incsearch.vim/issues/79

This is the NeoVim's problem, so I have no plan to fix it.
Disable VitalOverCommandLineCursor doesn't works because you cannot see the cursor position if you move cursor backward. NeoVim's cursor doesn't move correctly.

**Comment by ichbean** [comment]
Ok, sorry for bothering for such petty issue.

**Comment by haya14busa** [comment]
:+1:
