### ISSUE TITLE
Key not present in Dictionary

### ISSUE THREAD

**Issue by plateena** [easymotion/vim-easymotion#271]
After input the search character i got this error:
**Edit** : only happen when i change the map. when using the default map key it work fine.

Error detected while processing function EasyMotion#OverwinF..EasyMotion#overwin#move..<SNR>67_move..143..144..147..151:
line    1:
E716: Key not present in Dictionary: highlight_id_cursor)
E116: Invalid arguments for function matchdelete
Error detected while processing function EasyMotion#OverwinF:
line    4:
E171: Missing :endif
Error detected while processing function EasyMotion#OverwinF..EasyMotion#overwin#move..<SNR>67_move..143..144..147..151:

I have made troubleshoot step:

- Uninstall all plugin and Just install vundle, vimproc and easymotion
- reinstalling vimproc and exec make command
- changing map key 

Please help

**Comment by haya14busa** [comment]
> Edit : only happen when i change the map. when using the default map key it work fine.

Please note the mapping. I cannot reproduce it.

**Comment by plateena** [comment]
Start new vimrc and solve the proble. Solve. Sorry and tq for ur time.
