### ISSUE TITLE
beg for a little change of function EasyMotion#helper#load_migemo_dict to add a interface for custom migemo dict variable

### ISSUE THREAD

**Issue by jjwt** [easymotion/vim-easymotion#277]
i beg for a little change for that function, which can be like below
(I do not know vimL. So it may be wrong somewhere) :

```
function! EasyMotion#helper#load_migemo_dict() "{{{
    let enc = &l:encoding
    if exists('g:EasyMotion_migemo_dicts') && has_key(g:EasyMotion_migemo_dicts, enc)
        return g:EasyMotion_migemo_dicts[enc]
    endif
    if enc ==# 'utf-8'
        return EasyMotion#migemo#utf8#load_dict()
    elseif enc ==# 'cp932'
        return EasyMotion#migemo#cp932#load_dict()
    elseif enc ==# 'euc-jp'
        return EasyMotion#migemo#eucjp#load_dict()
    else
        let g:EasyMotion_use_migemo = 0
        throw "Error: ".enc." is not supported. Migemo is made disabled."
    endif
endfunction "}}}
```
only add the line 3-5, to add a interface with g:EasyMotion_migemo_dicts.
As a result ,i can create my own migemo dictionary in my vimrc someting like below:

```
  let g:EasyMotion_migemo_dicts = {
        \ 'utf-9':  { 'a': '\%([Aa]\)',
        \ 'B' : '\%([bB]\)',
        \ } ,
        \ 'cp932':  { 'a': '\%([Aa]\)',
        \ 'B' : '\%([bB]\)',
        \ } ,
        \ }

```

Thank you very much.

**Comment by jjwt** [comment]
@weakish maybe you like this way

**Comment by haya14busa** [comment]
#135 also can support custom migemo.

**Comment by jjwt** [comment]
@haya14busa So how do i make it work?
from #135 i try put in my vimrc 
```
  let g:EasyMotion_userdict = {
        \ '_' : {
        \     'd' : '\d\+'
        \   , '??' : '\v[!"#$%&''()=~|\-^\\@`[\]{};:+*<>,.?_/]+'
        \   , 'bb' : '\v[()[\]{}]+'
        \   , 'ee' : '[eæœèéêëēėęěə]'
        \   , 'ww' : '\(\<.\|^$\)'
        \   , '$$' : '$'
        \   , 'jk' : '^\(\w\|\s*\zs\|$\)'
        \   },
        \ }
```
or

```
let g:EasyMotion_user_dict  = {
            \ 'e' : '[eæœèéêëēėęěə]',
            \ 'nn' : '\v\c(nn|\d\+)',
            \ '??' : '[!"#$%&''()=~|\-^\\@`[\]{};:+*<>,.?_/]',
            \ }
```

but neither of them works.

Then i try to grep `g:EasyMotion_user_dict` or `g:user_dict` in the resource,
but find nothing. As a result, this feature has not been added ?

In other way, i think it's different from #135. i do not want a 
2-char dict , i just want a way to override the default dict given.
and i think the adding 3 lines won't do harm to other codes, but just
gives an interface to customer to extend or change the motion jump postions.

**Comment by haya14busa** [comment]
The feature is not merged yet. Try this branch https://github.com/Lokaltog/vim-easymotion/tree/feature/user-dictionary if you want.

`g:EasyMotion_user_dict` will do more than `g:EasyMotion_migemo_dicts` interface does. It's  fine not to use 2-char dict. I wont to provide only one interface for customizing character dictionary.

**Comment by jjwt** [comment]
i see, thank you, expecting it merged.
