### ISSUE TITLE
overwin commands don't show correct target keys

### ISSUE THREAD

**Issue by agilmor** [easymotion/vim-easymotion#278]
Hi,

When I use the -line or -w overwin commands, the highlight locations are correct, but the target keys shown don't. They are just the actual text, but highlighted (in red).
It seems that internally it has the correct target keys... but as don't see them I'm always getting the "Invalid target" error.

Thanks for such a great plugin!

Albert

**Comment by haya14busa** [comment]
I guess the problem is related with `conceal` feature overwin motion uses.

1. Please update the plugin since I fixed some related problem these days.
2. Please make reproduction steps. I cannot reproduce it.

**Comment by agilmor** [comment]
Thanks for so fast answer!
I've updated the plugin but same results.

But when trying to provide you with reproduction steps I've just realize that my  ```vim --version``` ouputs ```-conceal```... so it sounds like we find the problem?

I'm gonna try to rebuild my vim with this option enabled!

Thanks!

Albert

**Comment by agilmor** [comment]
Fixed!
It was the conceal.

Thanks!

PS: By the way, the ```--enable-conceal``` is not working anymore? I've used the ```--with-features=huge``` option.

**Comment by haya14busa** [comment]
Ok, I'll add a document about conceal #279

As for the build option, I'm not familiar with it, but I guess if you want a rich feature, i guess you should built vim with huge option in the first place?
