### ISSUE TITLE
conflicts with vim spell check

### ISSUE THREAD

**Issue by cinvro** [easymotion/vim-easymotion#280]
When I use easymotion to jump to another place, the spell check is disabled and cannot be recovered except restarting vim. 

Note this is only happen when there is more than one place matching my search.

**Comment by haya14busa** [comment]
I cannot reproduce it.
Please give me reproduction steps with minimal vimrc.

**Comment by cinvro** [comment]
1) :set spell
2) use  <Leader>s search for 2 chars (more than 1 locations fit)
3) jump to one location 

then the highlighted spell errors disappeared, use set spell cannot call them back.

vimrc as follows:   

    "" for easymotion
    map <Leader> <Plug>(easymotion-prefix)
    let g:EasyMotion_do_mapping = 0 " Disable default mappings
    " Jump to anywhere you want with minimal keystrokes, with just one key binding.
    nmap s <Plug>(easymotion-overwin-f2)
    "" Turn on case insensitive feature
    let g:EasyMotion_smartcase = 1
    "" JK motions: Line motions
    map <Leader>j <Plug>(easymotion-j)
    map <Leader>k <Plug>(easymotion-k)
    "" for spell
    hi clear SpellBad
    hi SpellBad cterm=underline

**Comment by haya14busa** [comment]
I cannot reproduce it with your vimrc.

Do you really try to reproduce the problem with the vimrc? If true, how? Pasting related lines from your entire vimrc doesn't always reproduce the problem.

**Comment by cinvro** [comment]
I changed my vimrc to the minimal one and I can reproduce the issue.

**Comment by haya14busa** [comment]
How did you load vim-easymotion with your vimrc? 

You can load plugin with your pasted vimrc (test.vimrc) like this.
```
vim --cmd 'set runtimepath+=~/.vim/mybundle/vim-easymotion' -u test.vimrc -N
```

Please try again. I cannot reproduce it.

**Comment by cinvro** [comment]
Sorry I didn't mention it, I load the plugin using Pathogen.

**Comment by cinvro** [comment]
I wonder if we are using the same version of vim-easymotion?

**Comment by cinvro** [comment]
[img][1]

[1]:https://dl.dropboxusercontent.com/u/49362521/easymotion.gif

**Comment by haya14busa** [comment]
Please execute highlight setting  on colorscheme change.
`autocmd MyVimrc ColorScheme * hi SpellBad cterm=underline`
