### ISSUE TITLE
option to change how the ```-ge``` behaves?

### ISSUE THREAD

**Issue by agilmor** [easymotion/vim-easymotion#281]
Hi!

Probably my brain is broken... but something that always disturbs it is the way that `ge` works on Vim.
The `w`, `b` and `e` are really natural to me, but not `ge`.

Just to quickly explain why, lets have this text:

```
hello wo[r]ld test
```

If I type `dw`,  or `de`or `db`, I get what I expect (respectively):

```
hello wo[t]est
hello wo[ ]test
hello [r]ld test
```

But when I type `dge` my brain expects

```
hello[r]ld test
```

but I get:

```
hell[l]d test
```

So, two thigs are wrong to my brain on this `ge` behaviour:
- the "inclusive" behavior on the initial character (removing the `[r]` of `world`)
  - the problem here is just that I feel that it's not consistent with `db` that also go backwards and keeps the `[r]`
  - if both `db` and `dge` remove the `[r]` it will be ok (or even better) to me (more consistent with `dw` and `de`: the current char is always included in all word motions)
- the "inclusive" behaviour to the target of my motion (removing the `o` of `hello`)
  - that's the most annoying part to my brain...
  - and I also feel that it's not consistent with the `dw`, that keeps the last chracter of my motion (the `t` of `test`)

The so great EasyMotion is consistent with the Vim behaviour, and that's good! ;-)
But I was just wondering if I can use EasyMotion also to _fix_ this `ge` behaviour...?

My idea is to add an option like `EasyMotion_fix_ge` to reduce the current `easymotion-ge` to one character at the beggining and at the end.  
I.e., from the current

```
hell[o wor]ld test
```

To:

```
hello[ wo]rld test
```

What do you think?

Thanks again for such a nice plugin!

Albert

PS: This is not an issue/bug, but a feature request.
PS: I don't want to argue against vim's `ge`, as I said, it's probably my brain! ;-)

**Comment by agilmor** [comment]
Hi!

I've just found this workaround to make the builtin ```ge``` as my brain expects:
http://vi.stackexchange.com/a/2448/6627

```
fu! MyCustomGE()
    return "\<c-u>:norm! ".v:count1."ge "
endfu
onoremap <leader>ge :<c-u><c-r>=MyCustomGE()<cr><cr>
```
It worked like a charm when used directly, but I've tested that EasyMotion keeps working as before even when overmapping the original ```ge```
```
onoremap ge :<c-u><c-r>=MyCustomGE()<cr><cr>
```

Now that at least I know a solution for the native ```ge```, I could try to do some hacking on the plugin...?
I'll let you know!

Thanks!

Albert

**Comment by haya14busa** [comment]
How about this?

```vim
function! s:easymotion_o_ge() abort
  call EasyMotion#go({'pattern': '\(.\>\zs\|^$\)', 'direction': 1, 'inclusive': 0})
endfunction
omap <Leader>ge :<C-u>call <SID>easymotion_o_ge()<CR>
```

**Comment by agilmor** [comment]
Thanks!
Yes, it works as a better ```easymotion_ge```!

But, is there a way to make it bidirectional?
I mean, I know that I can set ```direction``` to ```2```, but this motion removes an extra character for forward motions, right?

My idea is to make the ```easymotion-bd-e``` work like ```easymotion-bd-w```, but in the reverse way.
```easymotion-bd-w``` goes to the beginning of words and, if it goes backwards it includes the first character of the word in operators, but if it goes forward, it doesn't.
So, I would like a ```easymotion-bd-e``` to go to the end of words and, if it goes forward it includes the last character of the word in the operators, but if it goes backward, it doesn't.


Thanks!

Albert

**Comment by haya14busa** [comment]
I don't have any plan to work on this now, sorry but I'll close this issue for now.
