### ISSUE TITLE
easymotion-overwin-* not working on Mac OS X

### ISSUE THREAD

**Issue by karamellpelle** [easymotion/vim-easymotion#284]
I get errors while using all (?) of the `easymotion-overwin-*` commands:

    function EasyMotion#overwin#w..EasyMotion#overwin#move..<SNR>46_move..1..2..5..23..24..14, line 23:Vim(if):E118: Too many arguments for function: getbufvar
    Error detected while processing function EasyMotion#overwin#w..EasyMotion#overwin#move..<SNR>46_move..1..2..5..9..15..<SNR>46_throw:
    line    1:
    E605: Exception not caught: vital: HitAHint.Motion: function EasyMotion#overwin#w..EasyMotion#overwin#move..<SNR>46_move..1..2..5..9..15, line 20 Vim(if):E118: Too many arguments for function: getbufvar
    Press ENTER or type command to continue

This happens on Mac OS X El Capitan with zsh (_zsh 5.0.8 (x86_64-apple-darwin15.0)_). On my Linux computer, there is no error. My vimfiles are under git control so they are the same on both computers.

Thank you very much for the _vim-easymotion_ plugin! I started using it for some hours ago, and I am pretty sure it's going to boost my productivity significantly :) :frog:

**Comment by haya14busa** [comment]
>  Vim(if):E118: Too many arguments for function: getbufvar

I guess your Vim version on Mac OS is old. What vim version do you use on Mac?

**Comment by karamellpelle** [comment]
Thank you, that is a good point,

    > vim --version                
    VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2015 16:22:14)
    Compiled by root@apple.com

This is the vim given by Apple. What is recommended update procedure for vim on Mac? brew?

**Comment by karamellpelle** [comment]
Updating vim to 7.4 solved this problem. Thank you @haya14busa 

I used _homebrew_ to install vim, and created an alias for my shell that overrided the vim given by Apple.

**Comment by haya14busa** [comment]
Thanks.

> I used homebrew to install vim, and created an alias for my shell that overrided the vim given by Apple.

Actually, it seems there was a bug to handle MAC OS X yeasterday and https://github.com/easymotion/vim-easymotion/commit/a6b3c10b417d90d6751352b53826f94062ff466d solves it.
Thank you for the report!
