### ISSUE TITLE
Vim enters insert mode on <Leader>s

### ISSUE THREAD

**Issue by alistaircolling** [easymotion/vim-easymotion#286]
Hi, `<Leader>k` and `<Leader>j` work fine but when I press `<Leader>s` Vim enters insert mode.

Can anyone help?

Thanks!

Easymotion 3.0
Vim 7.4.903

**Comment by haya14busa** [comment]
map `<Leaders` explicitly in your vimrc like this `nmap <Leader>s <Plug>(easymotion-overwin-f2)`
