### ISSUE TITLE
easymotion-overwin-f2 doesn't work for filetype=text?

### ISSUE THREAD

**Issue by somespec** [easymotion/vim-easymotion#287]
Hi, I recently discovered `easymotion-overwin-f2` which is pretty cool. One problem I'm having is that this feature seems to not work when the filetype is 'text' or '' (filetype not set, like when I newly open Vim). It works perfectly for other filetypes I've been editing. By not work I mean, for example, I would expect the word `example` to be something like `{a}xample` when I type `ex` after easymotion asks me to `Search for 2 characters: ` but what happens is the first character disappears, the word shifts one character to the left and it shows `xample`. I'm using the latest commit a6b3c10b417d90d6751352b53826f94062ff466d of easymotion on Vim 7.4 (patches 1-1665).

Haven't had time to fully explore so I might be doing something wrong, but just wanted to report you. Thanks for an awesome plugin!

**Comment by haya14busa** [comment]
Thanks for the report. I also noticed this behavior, I'll look into it.

**Comment by haya14busa** [comment]
It was Vim's bug and I fixed this issue. https://github.com/vim/vim/commit/4d58502 .
Please update Vim.

**Comment by somespec** [comment]
Updated Vim and working fine. Interesting so it was Vim's bug. Cool, thanks!

**Comment by alencool** [comment]
Im having this exact issue using NVIM v0.1.5-685.

**Comment by zweicoder** [comment]
I'm getting this for vim 7.4 when editing `.csv` files when using `easymotion-overwin-f`
