### ISSUE TITLE
Text object support

### ISSUE THREAD

**Issue by IngoHeimbach** [easymotion/vim-easymotion#289]
Vim text objects are great to speed up editing performance but sometimes they are a bit cumbersome to use. Example:

```
(x * (y _+ z))
```

(The cursor position is marked with `_`.)
Selecting the contents of the outer parentheses can be done by using a builtin text object like `2i)` but it is difficult to recognize the nesting level if the expressions become longer. 
It would be great if easy motion could also be used for text objects by marking the different levels of parentheses with letters.

**Comment by haya14busa** [comment]
It could be useful but I doubt this feature should be provided by default.

I plan to provide API which receives target positions  and perform easymotion-style jump to them.
So, once I create the api, you can create easymotion-plugin to support text-object by gathering target positions and pass them to the easymotion API.

**Comment by IngoHeimbach** [comment]
Sounds good! :)

**Comment by haya14busa** [comment]
it's undocumented, but please use `Easymotion#go`
