### ISSUE TITLE
n-character search motion

### ISSUE THREAD

**Issue by pdoak** [easymotion/vim-easymotion#291]
Is it possible to change the n-character search motion to automatically use "very magic". For example, when invoked with `/`, it becomes `/\v` automatically.

**Comment by haya14busa** [comment]
I have no plan to implement it, but I already implement the feature in incsearch.vim.
You can integrate incsearch.vim with easymotion, so please use incsearch.vim with easymotion. re: https://github.com/easymotion/vim-easymotion/issues/256#issuecomment-172363769
