### ISSUE TITLE
Change motion off by one char when multiple splits of different buffers

### ISSUE THREAD

**Issue by thalesmello** [easymotion/vim-easymotion#292]
In an empty buffer, type in:

```
print('hello world')
```

Then, with the cursor in the in the first position, type `c<leader><leader>f'a`. As expected, the output is:

```
hello world')
```

Now, press `u` to undo and create a split with an empty buffer using `:vnew`.
Apply the same `c<leader><leader>f'a` at the beginning of the first buffer text. The resulting output is:

```
'hello world')
```

Which I believe is a bug. I've noticed it only acts when live editing the code. If you `u` undo the operation and `.` repeat it with `vim.repeat`, it applies the correct behavior. And, if you close the newly spawned buffer with `:q`, the correct operation starts to work again.

**Comment by thalesmello** [comment]
This issue appears to be related to the FastFold plugin. Look at [this issue](https://github.com/Konfekt/FastFold/issues/38)

**Comment by Konfekt** [comment]
This could be solved by `easymotion` by adding to
```vim
call setbufvar('%', a:var, s:var_reset[a:var])
```
in helper.vim the check
```vim
if getbufvar('%', a:var) isnot s:var_reset[a:var]
  call setbufvar('%', a:var, s:var_reset[a:var])
endif
```
Because this function sets the foldmethod to `manual` and restores it. Thereby it triggers the OptionSet autocmd from FastFold, which leads to the bug reported in this issue. Unnecessarily so, because the foldmethod is always `manual` with FastFold.

**Comment by thalesmello** [comment]
@Konfekt I've tried modifying easymotion with the change you suggested, but the problem didn't go away.

**Comment by Konfekt** [comment]
Strange. By commenting it out, it does though ?

**Comment by thalesmello** [comment]
Yes. It indeed goes away.

@haya14busa What does EasyMotion#helper#VarReset (in autoload/EasyMotion/helper.vim) do?

**Comment by Konfekt** [comment]
My wording was confusing: By 'adding' meant was 'replacing'. In the end it is probably a Vim issue.

**Comment by haya14busa** [comment]
It seems FastFold fixed the problem. https://github.com/Konfekt/FastFold/issues/38
