### ISSUE TITLE
easymotion-overwin-f fails

### ISSUE THREAD

**Issue by reckbo** [easymotion/vim-easymotion#293]
I have this binding in my vimrc:

```
nmap s <Plug>(easymotion-overwin-f)
```

but get the error below when I use it.  Any idea what's going on?

Thanks,
Ryan

---

Error detected while processing function EasyMotion#OverwinF..EasyMotion#overwin#move..<SNR>127_move..643..644..647..651..657..<SNR>127_throw:
line    1:
E605: Exception not caught: vital: HitAHint.Motion: function EasyMotion#OverwinF..EasyMotion#overwin#move..<SNR>127_move..643..644..647..651..657, line 20 Vim(if):E118: Too many arguments for function:
getbufvar
Error detected while processing function EasyMotion#OverwinF:
line    4:
E171: Missing :endif

**Comment by madwed** [comment]
I get this same issue, with `map f ...(etc)`, `nmap f ...(etc)`, `map w ...(etc)`, `nmap w ...(etc)` in my `vimrc`

**Comment by mikekolganov** [comment]
Guys, I just solved this by adding `set shell=bash\ -i` to .vimrc.
Inspired by https://github.com/suan/vim-instant-markdown/issues/41

Thanks,
Mike

**Comment by haya14busa** [comment]
> Vim(if):E118: Too many arguments for function:
getbufvar

Please update Vim. Your vim version seems too old.
