### ISSUE TITLE
Overwin motions with vim-maximizer

### ISSUE THREAD

**Issue by karamellpelle** [easymotion/vim-easymotion#297]
Hello! I have a problem with _vim-easymotion_ + _vim-maximizer_. _vim-maximizer_ is a plugin to toggle focused windows to/from fullscreen, https://github.com/szw/vim-maximizer). When one of my windows is shrunk (done by _vim-maximizer_) and I do overwin movements, like `easymotion-overwin-w`, that movement opens up (to highlight the key(s) moves in that window) the shrunk window. And then the window toggling does not work (so then I reset all windows with `CTRL-W =`).

Is it possible to prevent _vim-easymotion_ from increasing the sizes of current windows?

**Comment by haya14busa** [comment]
I didn't understand what vim-maximizer do, but anyway, I don't have any plan to work on this now.

Please reopen with more detail reproduction steps or try to contact to the author of vim-maximizer.
