### ISSUE TITLE
\w not working with overwin (cross windows) - lines above not hightlighting

### ISSUE THREAD

**Issue by tamnil** [easymotion/vim-easymotion#298]
leader - w  not working on raw text with overwin.
itś supressing  the shortcuts.
For syntax enabled (coloured - php, html, *.md, etc) it is working fine.
without overwin it works too.
nmap <Leader>w <Plug>(easymotion-overwin-w)  
![screenshot from 2016-06-24 05-19-01](https://cloud.githubusercontent.com/assets/6069081/16332217/4438c12a-39cb-11e6-95bd-448c6acc727d.png)

**Comment by haya14busa** [comment]
dup https://github.com/easymotion/vim-easymotion/issues/287

please update vim
