### ISSUE TITLE
Difference between `bd-jk` and `overwin-line`

### ISSUE THREAD

**Issue by unclechu** [easymotion/vim-easymotion#299]
As doc says:

> `<Plug>(easymotion-overwin-line)` is like `<Plug>(easymotion-bd-jk) but supports moving cursor to other window.

But `<Plug>(easymotion-overwin-line)` moves cursor at start of the line and `<Plug>(easymotion-bd-jk)` moves cursor to first non-white-space character of line. There's any `-overwin-` equivalent of `<Plug>(easymotion-bd-jk)`?

**Comment by haya14busa** [comment]
I think it's not useful to preserve column for overwin motions.
