### ISSUE TITLE
need to change the green color when searching.

### ISSUE THREAD

**Issue by ri-aje** [easymotion/vim-easymotion#300]
this is a dup of issue #261 . the author seemed not able to repro the bug by then, and I provided additional information but didn't get any reply yet. so I am creating a new one to seek attention. 

here is my case. basically I only use `easymotion-sn`. in there, after I invoke the functionality and start typing but before finally settling down on any target by pressing the enter key, easymotion will highlight matches incrementally, but the highlighting color is always green, which is not very visible in a light color theme that I use.

I tried modifying `EasyMotionMoveHL` to various colors but I don't see any difference for the green matches. I also tried setting `g:EasyMotion_move_highlight` to 0 and 1, and played with all the combinations with `EasyMotionMoveHL`, and that doesn't seem to bring any difference either.

I read the docs and `g:EasyMotion_move_highlight` seems to be controlling `easymotion-next/prev` which is not what I use.

can someone repro this? and if so, fix it? Thanks.

**Comment by dcapo** [comment]
I also ran into this. Reproduced in MacVim and iTerm2.

**Comment by haya14busa** [comment]
Please use `EasyMotionIncCursor` instead

**Comment by dcapo** [comment]
I think you meant `EasyMotionIncSearch`, but it worked, thanks!
