### ISSUE TITLE
suggest add search first character of all words by enter one search key

### ISSUE THREAD

**Issue by pangchol** [easymotion/vim-easymotion#302]
I find search all character by enter one（or two）serach key offen need enter 4 keys to jump to target(one key start easymothon-s, one (or two) keys  enter search keys, becasue search out too many target, at last, we need two keys to jump to finally target). I think too many search target cause by easymotion  seach the all characters in cruuent screen. how to reduce search target? a easy way is just search all word's first character. because we jump to one target offen is want to jump to the word's header or tail. so I think this kind of jump is frequently-used. so I suggest to add this kind of easymotion mode， this mode can search first character of all words in current screen by enter one search key. this mode will bring a function that can jump to a finally target by just press 3 keys!!!

**Comment by haya14busa** [comment]
I don't have any plan to work on this now. I thinks `<Plug>(easymotion-s2)` is enough.
