### ISSUE TITLE
In Neovim, target keys are invisible for certain extensions like .txt, .md, etc., while they are not in vim 7.4

### ISSUE THREAD

**Issue by kimdhyungg** [easymotion/vim-easymotion#303]
Dear developers of this awesome plugin,

In Neovim, when the following plug is triggered in a file with an extension such as .txt, .md,

```
 <Plug>(easymotion-overwin-f)  // not tested for other plugs, since I'm only using this.
```

the target keys (which are supposed to appear in red letters) disappear, not even leaving a single blank. For example, let us say we search for a letter 'h' from the following text: "Hello world! Hehehe", It becomes "ello world! eee" and the target keys are invisible. It seems like the function itself is still working since I sometimes go to a random place if I press a random key, and the text is recovered. It is just not visible. 

I would like to give you some of my discoveries regarding this issue.
The first one is that it works totally well in other extensions (which have colorful syntax highlighting) such as .c or .vimrc in Neovim.
The second is that it works totally well in (not-neo) vim 7.4 even for the .txt or .md extensions.
The third is that if I trigger a highlighting plugin called 'jaxbot/semantic-highlight.vim', then the above issue will be solved temporarily until I quit the file. After it starts functioning normally, it continues to work no matter if I untrigger 'semantic-highlight' or not.

So, my (not-so-trustworthy) inference is that this is an issue related to Neovim's 'red color' hightlighting mechanism for different extensions. 
I'm currently using Molokai colorsheme, just for your information, and it has supports for various colors including the important 'red'. However for .txt or .md extensions, their syntax highlighting is very simple and the 'red color' is not required. Perhaps Neovim might be disabling the red color (and maybe others too) from the initialization while reading through 'init.vim' file for some kind of optimization reasons, thinking that the user (in this case, I) will never need it. Probably that's the reason 'easy-motion' cannot use 'red color' for representing the targets in .txt or .md. But the color will be available if 'semantic-highlight' is triggered since the plugin might have a function to enable colors back. And that explains the temporary fix.  
 Again, be careful because this is just purely my assumption without any verification.

I often write letters or essays in vim and easy-motion is a wonderful partner to navigate a bunch of paragraphs. I recently switched to neovim and I'm really sad since it does not work for .txt or .md. I guess I can temporarily solve this issue by writing those essays in .c extension but, you know, it sounds not cool. 
Thank you!

Sincerely,

**Comment by NovaDev94** [comment]
I'm having the same problem. This only happens with Neovim and overwin-motions (easymotion-s, easymotion-s2,... works fine).

**Comment by haya14busa** [comment]
Thank you for the report.

Could you please see this pr https://github.com/easymotion/vim-easymotion/issues/287 and making sure this patch patch vim/vim@4d58502  is ported to neovim?

**Comment by NovaDev94** [comment]
Thanks a lot @haya14busa. Patch 7.4.1740 wasn't ported to neovim, made a PR here for the port https://github.com/neovim/neovim/pull/5366. Hopefully it'll get approved soon.

**Comment by haya14busa** [comment]
Seems neovim/neovim#5366 is merged
