### ISSUE TITLE
What is the <Plug> key?

### ISSUE THREAD

**Issue by drozzy** [easymotion/vim-easymotion#306]
How do I switch vim-easymotion to work on single lone mode?

Just like in this video:
https://youtu.be/oMnK_llHoK8

I have no idea what this means:

`<Plug>(easymotion-sl), <Plug>(easymotion-bd-wl),`

What is `Plug`? And how do I remap my `\\w` and `\\f` to it?

Thanks!

**Comment by Shougo** [comment]
`:help <Plug>`

```
							*<Plug>*
The special key name "<Plug>" can be used for an internal mapping, which is
not to be matched with any key sequence.  This is useful in plugins
|using-<Plug>|.
```

**Comment by Shougo** [comment]
>And how do I remap my `\\w` and `\\f` to it?

```vim
nmap \\w  <Plug>(easymotion-sl)
nmap \\f  <Plug>(easymotion-bd-wl)
```

**Comment by drozzy** [comment]
Thanks a bunch.
