### ISSUE TITLE
incsearch incsearch-fuzzy vim-easymotion incsearch-easymotion

### ISSUE THREAD

**Issue by 3xp10it** [easymotion/vim-easymotion#307]
I have installed those 4 plugins:
    incsearch incsearch-fuzzy vim-easymotion incsearch-easymotion
but can not find a way to make all of them work,in my ubuntu 16.04 system,I can not use incsearch-fuzzy plugin's function to fuzzy search,can you help me about how to set vimrc while I installed those 4 plugins?

my vimrc setting about those 4 plugins are in below:

"111111incsearch插件设置
""""""""""start of incsearch"""""""""
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

set hlsearch
let g:incsearch#auto_nohlsearch = 1
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map \*  <Plug>(incsearch-nohl-_)
map #  <Plug>(incsearch-nohl-#)
map g_ <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

function! s:noregexp(pattern) abort
    return '\V' . escape(a:pattern, '\')
endfunction

function! s:config() abort
    return {'converters': [function('s:noregexp')]}
endfunction

noremap <silent><expr> z/ incsearch#go(<SID>config())
""""""""""end of incsearch""""""""""

"222222incsearch-fuzzy插件设置
"""""""""start of incsearch-fuzzy"""""""""
"fuzzy
map z/ <Plug>(incsearch-fuzzy-/)
map z? <Plug>(incsearch-fuzzy-?)
map zg/ <Plug>(incsearch-fuzzy-stay)

fuzzyspell
map z/ <Plug>(incsearch-fuzzyspell-/)
map z? <Plug>(incsearch-fuzzyspell-?)
map zg/ <Plug>(incsearch-fuzzyspell-stay)

"Use both fuzzy & fuzzyspell feature
function! s:config_fuzzyall(...) abort
    return extend(copy({
  \   'converters': [
  \     incsearch#config#fuzzy#converter(),
  \     incsearch#config#fuzzyspell#converter()
  \   ],
  \ }), get(a:, 1, {}))
endfunction
noremap <silent><expr> z/ incsearch#go(<SID>config_fuzzyall())
noremap <silent><expr> z? incsearch#go(<SID>config_fuzzyall({'command': '?'}))
noremap <silent><expr> zg? incsearch#go(<SID>config_fuzzyall({'is_stay': 1}))

"""""""""end of incsearch-fuzzy"""""""""

"333333incsearch-easymotion插件的设置
map z/ <Plug>(incsearch-easymotion-/)
map z? <Plug>(incsearch-easymotion-?)
map zg/ <Plug>(incsearch-easymotion-stay)

incsearch.vim x fuzzy x vim-easymotion
function! s:config_easyfuzzymotion(...) abort
          return extend(copy({
            \   'converters': [incsearch#config#fuzzy#converter()],
            \   'modules': [incsearch#config#easymotion#module()],
            \   'keymap': {"<CR>": '<Over>(easymotion)'},
            \   'is_expr': 0,
            \   'is_stay': 1
            \ }), get(a:, 1, {}))
endfunction
noremap <silent><expr> <Space>/ incsearch#go(<SID>config_easyfuzzymotion())

"下面是easymotion插件的相关设置
""""""""""""""""""start of easymotion""""""""""""""""""
"下面这句暂时不确定用意
let g:EasyMotion_do_mapping = 0 " Disable default mappings
"三键到任意地方
nmap s <Plug>(easymotion-overwin-f)
"四键到任意地方
"nmap s <Plug>(easymotion-overwin-f2)
"设置大小写不敏感
let g:EasyMotion_smartcase = 1
" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
"move to line 
map <Leader>l <Plug>(easymotion-bd-jk)
nmap <Leader>l <Plug>(easymotion-overwin-line)

"下面设置fuzzsearch,这个有点叼,结合incsearch,incsearch-fuzzy,easymotion,incsearch-easymotion四个插件
" You can use other keymappings like <C-l> instead of <CR> if you want to
" use these mappings as default search and somtimes want to move cursor with
" EasyMotion.
function! s:incsearch_config(...) abort
          return incsearch#util#deepextend(deepcopy({
            \   'modules': [incsearch#config#easymotion#module({'overwin': 1})],
            \   'keymap': {
            \     "<CR>": '<Over>(easymotion)'
            \   },
            \   'is_expr': 0
            \ }), get(a:, 1, {}))
endfunction

noremap <silent><expr> /  incsearch#go(<SID>incsearch_config())
noremap <silent><expr> ?  incsearch#go(<SID>incsearch_config({'command': '?'}))
noremap <silent><expr> g/ incsearch#go(<SID>incsearch_config({'is_stay': 1}))
""""""""""""""""""end of easymotion""""""""""""""""""

**Comment by haya14busa** [comment]
```vim
function! s:config_easyfuzzymotion(...) abort
return extend(copy({
\ 'converters': [incsearch#config#fuzzy#converter()],
\ 'modules': [incsearch#config#easymotion#module()],
\ 'keymap': {"": '(easymotion)'},
\ 'is_expr': 0,
\ 'is_stay': 1
\ }), get(a:, 1, {}))
endfunction
noremap / incsearch#go(config_easyfuzzymotion())
```
