### ISSUE TITLE
'type command to continue' prompt shown on cancel

### ISSUE THREAD

**Issue by rhysd** [easymotion/vim-easymotion#308]
## Config

```vim
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
map : <Plug>(easymotion-overwin-f2)
```

## Repro

1. Open Vim
2. Enter `:` then easymotion's prompt will be shown
3. Enter `<Esc>`
4. easymotion echos two lines hence 'type command to continue' prompt prevents user input

## ScreenShot

![tmp](https://cloud.githubusercontent.com/assets/823277/19444994/a319153e-94cd-11e6-867f-76eb59402f47.gif)

## Environment

- vim-easymotion: 5c6f3cd (latest)
- Vim: v8.0-3 (MacVim)
- OS X 10.11

**Comment by rhysd** [comment]
It seems that below mapping doesn't cause this problem.

```vim
map gs <Plug>(easymotion-overwin-f2)
```

**Comment by haya14busa** [comment]
Thanks for the report. I'll look into it later :dog:

**Comment by haya14busa** [comment]
Hmm... I cannot reproduce it with Vim 8.0.27 in CLI nor gvim.

**Comment by rhysd** [comment]
OK, I'll make a minimal config.

**Comment by rhysd** [comment]
I confirmed with below `.vimrc`.  `cedit` option seems to cause this.

```vim
set nocompatible

set cedit=<C-c>

set rtp+=~/.vim/bundle/vim-easymotion/

let g:EasyMotion_do_mapping = 0
map : <Plug>(easymotion-overwin-f2)

" vim: set ft=vim fdm=marker ff=unix fileencoding=utf-8:
```

**Comment by haya14busa** [comment]
Thanks. I can reproduce it as well.

Hmmm... I'm not sure but it could  be related with this issue https://github.com/easymotion/vim-easymotion/issues/177
https://github.com/osyo-manga/vital-over/issues/52

```vim
function! s:module.redraw(cmdline)
	redraw
	" Workaround for the :set cedit=<C-c>
	" https://github.com/osyo-manga/vital-over/issues/52
	" https://github.com/Lokaltog/vim-easymotion/issues/177#issuecomment-53663431
	if &cedit != "<C-c>"
\	||(v:version >= 704 && has("patch441"))
		normal! :
	else
		execute "normal! :\<Esc>"
	endif
endfunction
```

version check condition is wrong... I'll send a pull-request to vital-over. thanks. 
I think this fix the issue (at least it seems to be fixed in my environment by this patch)

```diff
diff --git a/autoload/vital/_easymotion/Over/Commandline/Modules/Redraw.vim b/autoload/vital/_easymotion/Over/Commandline/Modules/Redraw.vim
index 5c22d91..c75e2b0 100644
--- a/autoload/vital/_easymotion/Over/Commandline/Modules/Redraw.vim
+++ b/autoload/vital/_easymotion/Over/Commandline/Modules/Redraw.vim
@@ -56,7 +56,7 @@ function! s:module.redraw(cmdline)
 	" https://github.com/osyo-manga/vital-over/issues/52
 	" https://github.com/Lokaltog/vim-easymotion/issues/177#issuecomment-53663431
 	if &cedit != "<C-c>"
-\	||(v:version >= 704 && has("patch441"))
+\	||(v:version > 704 || v:version == 704 && has("patch441"))
 		normal! :
 	else
 		execute "normal! :\<Esc>"
```

**Comment by rhysd** [comment]
It also looks to work for me. Thanks 👍

**Comment by haya14busa** [comment]
fyi: the p-r is included and I updated easymotion.
