### ISSUE TITLE
how to use the normal key 's' when installed easymotion?

### ISSUE THREAD

**Issue by 3xp10it** [easymotion/vim-easymotion#309]
can I use normal key 's' to get "delete and insert" effect，'S' key is ok,but what is a good idea to bind some key to 's' to get "delete and insert" effect.
                                                                                 Thx.

**Comment by haya14busa** [comment]
easymotion doen't overwride normal key 's' by default.

```
nmap {use-whatever-key-you-want} <Plug>(easymotion-overwin-f2)
```
