### ISSUE TITLE
Conflict with vim-orgmode and easymotion

### ISSUE THREAD

**Issue by yamsu** [easymotion/vim-easymotion#311]
If i use the easymotion mechanism in an org file, with the vim-orgmode plugin, after the motion complete vim shows the following in the message bar and expects a return press.
Target key:
EasyMotion: Jumping to [131, 27]
Press ENTER or type command to continue

This issue is not there when the vim-orgmode plugin is diabled and of course doesn't occur when a non  org file is edited. 

Has anyone else faced this problem? Is there are work around or does this need a fix? Look forward to any solutions thanks.

**Comment by yamsu** [comment]
Using vim 8, with easy motion 3.0

**Comment by haya14busa** [comment]
As a workaround, `let g:EasyMotion_verbose = 0` might fix the problem by not showing easymotion messages.

**Comment by yamsu** [comment]
Thanks for the prompt response! Yes the addition of "let g:EasyMotion_verbose = 0" solves the problem.
Great plugin!!!
