### ISSUE TITLE
Line # Difference easymotion-j/easymotion-k

### ISSUE THREAD

**Issue by matrinox** [easymotion/vim-easymotion#312]
`easymotion-j` starts counting on the next line
`easymotion-k` starts counting on the current line. Is that intended?

**Comment by haya14busa** [comment]
I cannot reproduce it

**Comment by haya14busa** [comment]
Please reopen with detail reproduction steps

**Comment by matrinox** [comment]
If you select text that is not in the start of the line, it does that.
Steps:
1. Select text that is not sol
2. easymotion-k
Expected: starts on line above
Actual: starts on current line

**Comment by haya14busa** [comment]
You can set `let g:EasyMotion_startofline = 0` to exclude current line.
