### ISSUE TITLE
Invoking easymotion in VimScript

### ISSUE THREAD

**Issue by amacfie** [easymotion/vim-easymotion#313]
This function

    function! Func()
      execute "normal \<Plug>(easymotion-s2)ab"
      echo "done"
    endfunction

just prints

    EasyMotion: Cancelled
    done

when called.
What I'm trying to do is run the easymotion command normally (which searches for `ab` in this case), with the user input and jump, then print `done` at the end, not cancel it.
Is there a way to do that?

**Comment by haya14busa** [comment]
Please use `EasyMotion#go`, it's undocumented though

**Comment by physicophilic** [comment]
I had a similar issue.

After digging in the code, I was able to use `EasyMotion#User('pattern', visualmode, direction, inclusive)` to get a job almost done, but I face a problem - I understand how to use `pattern` and the `direction`, but I don't know how to enable `visualmode` (and `inclusive`, but that's not important.)

Can you help?
