### ISSUE TITLE
Open links

### ISSUE THREAD

**Issue by karamellpelle** [easymotion/vim-easymotion#315]
Is there a command to emphasize and open links? For example inside the vim help you can click in on subjects in the table of contents and jump to it. For now, I move to words (with `<Leader>w`) and then open the link.

**Comment by haya14busa** [comment]
You can just pres `<C-]>` after moving cursor. I do not think it's useful to implement it in easymotion.

**Comment by wsdjeg** [comment]
@haya14busa do you use vimperator in firefox, or ace-link, I think this feature request is for something like this, would you like to add this feature?
