### ISSUE TITLE
[Suggestion] n-character search motion - trigger after delay

### ISSUE THREAD

**Issue by deathmaz** [easymotion/vim-easymotion#316]
Hi @haya14busa, there's a plugin for emacs called [avy](https://github.com/abo-abo/avy), it works pretty similar to vim-easymotion, but also it has [avy-goto-char-timer](https://github.com/abo-abo/avy#avy-goto-char-timer) feature, which works like `n-character search motion` but triggers after some delay, so you don't need to press `Enter` to trigger.

Is it possible to add this feature to `vim-easymotion`?

Thank you very much for your effort!

**Comment by haya14busa** [comment]
It's possible to implement it but I doubt the timer feature is really useful.

You can use https://github.com/haya14busa/incsearch-easymotion.vim and create a timer plugin for incsearch.vim to implement it.

**Comment by ankitp4t3l** [comment]
I agree with Hans. I feel as if I intuitively know to type more characters in buffers full of text and less characters in buffers that have less characters.

The timer feature allows you to pick how many characters to type per invocation.

Using 1-char or 2-char forces you to choose if you only use one key to trigger easymotion/avy (`s` for me).
