### ISSUE TITLE
IdealVim plugin

### ISSUE THREAD

**Issue by brucechou1983** [easymotion/vim-easymotion#317]
This plugin really helps me a lot when using vim. Recently I start using IdealVim in Jetbrains products like WebStorm and PyCharm. Although there is anther similar plugin called `acejump`, it's a bit less effective than `vim-easymotion`.

Is there any plan to migrate this project to IdealVim? Thanks!

**Comment by haya14busa** [comment]
I don't have any plan to use IdeaVim.

Please contact to IdeaVim or use Vim instead ;)
