### ISSUE TITLE
Disable default mapping doesn't work

### ISSUE THREAD

**Issue by JulioJu** [easymotion/vim-easymotion#320]
Hi,

With a minimal vimrc and an emplty ".vim" (only with vim-plug and Easymogtion) `let g:Easymotion_do_mapping=0` doesn't work. 

I've tested with Neovim and Vim, with following ".vimrc" : 
```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'Lokaltog/vim-easymotion'
call plug#end()
filetype plugin indent on
let g:Easymotion_do_mapping=0
```

Thanks in advance

**Comment by haya14busa** [comment]
I cannot reproduce it. Please check your vimrc is correctly loaded.
maybe you can check by adding `echom "g:Easymotion_do_mapping =" g:Easymotion_do_mapping` at the bottom.

**Comment by haya14busa** [comment]
Please reopen with reproduction steps.

**Comment by JulioJu** [comment]
Hi, 
Excuse-me for not having answered sonner.
Vimrc is correctly loaded, I use command `nvim essai.md -u /tmp/vimrclight`.
`echom "g:Easymotion_do_mapping =" g:Easymotion_do_mapping` print => `g:Easymotion_do_mapping = 0`.
Howerver, when we type for exemple 
```
\\f
```
Easymotion display "Search for 1 character:"
Thinks in advance !

**Comment by marekzidek** [comment]
Did you open a new issue, or found a solution?

**Comment by HungPham3112** [comment]
I have the same problem, please help

Reproduce:
step 1: add `let g:Easymotion_do_mapping=0` in `vimrc `
step 2: use `<leader><leader>f `and it still use default `<Plug>(easymotion-f)`
