### ISSUE TITLE
Limiting easymotion's use of grouping

### ISSUE THREAD

**Issue by jan-warchol** [easymotion/vim-easymotion#321]
Very nice plugin!

However, I'm having the following usability issue: I often have a lot of code visible, so that when using the word motion there are hundreds of targets. The result is that even the closest targets (in which I'm usually interested the most) require two-letter motions.

I would like to tell EasyMotion to reserve X characters for single-letter hints for the closest targets (so that if there are so many targets easymotion will use 1-letter hints for the closest targets and 3-letter hints for the farthest ones, rather than using 2-letter hints for all of them).

**Comment by haya14busa** [comment]
I don't have plan to implement this idea. PR are welcome but 
I think it's better to use two-character search or something to suppress too many matches in the first place.
