### ISSUE TITLE
Using vim-easymotion with Neovim's :terminal in normal mode. 

### ISSUE THREAD

**Issue by tecfu** [easymotion/vim-easymotion#322]
I am attempting to use vim-easymotion in Neovim's :terminal. 

Steps:

1. Open Neovim's terminal.
```
:terminal
```

2. Enter normal mode while in the terminal buffer. 
```
<C-\><C-n>
```

3. Activate vim-easymotion
```
f
```

4. See error messages:
```
EasyMotion: Vim(call):E21: Cannot make changes, 'modifiable' is off : function EasyMotion#S[11]..<SNR>215_EasyMotion[226]..<SNR>215_PromptUser[172]..<SNR>
215_SetLines, line 2
```

The discussion here https://github.com/neovim/neovim/issues/2607#issuecomment-205636270 suggests this could be easily fixed....

**Comment by haya14busa** [comment]
dup #246

The comment https://github.com/neovim/neovim/issues/2607#issuecomment-205636270 is wrong.
easymotion needs to modify buffer still in latest and no plan to fix this issue (or I should say I cannot in current feature of vim (or neovim)).

**Comment by tecfu** [comment]
Thanks for the feedback.
