### ISSUE TITLE
indentLine Concealed Characters Colored as Targets

### ISSUE THREAD

**Issue by yarko3** [easymotion/vim-easymotion#328]
Hi,
Thanks for the great plugin. I have an issue with how easymotion sometimes interacts with yggdroot/indentLine. The indent characters provided by indentLine sometimes show in the same color as targets of easymotion when easymotion is triggered. This issue is not consistent for all splits on screen and if I open a new file in the same buffer, the issue does not always persist. Also opening the offending file in a different split does not persist the issue. 

Will try to reproduce at home and post a screenshot. 

My .vimrc is here:
https://github.com/yarko3/dotfiles/blob/master/vim/startup/plugins.vim

**Comment by yarko3** [comment]
Here's a screenshot: 
![screenshot from 2017-04-19 23-11-24](https://cloud.githubusercontent.com/assets/6383866/25211891/8e3ae50c-2555-11e7-83ae-e0c806a632a1.png)

**Comment by haya14busa** [comment]
Do you use latest vim-easymotion?

**Comment by yarko3** [comment]
Yeah, I'm on the newest version of easymotion. 

I think the flow that triggers this for me is:
- grep with Grepper
- open a result from quickfix window in a split

**Comment by yarko3** [comment]
I noticed that the issue shows on neovim as well.

**Comment by yarko3** [comment]
Closing issue as I haven't experienced this in a long while.

**Comment by DasOhmoff** [comment]
Hello, I have this exact same issue. How did you fix this?
I am using vim on windows.
Did you change your setup?
