### ISSUE TITLE
How to work in insert mode?

### ISSUE THREAD

**Issue by zgqq** [easymotion/vim-easymotion#329]
```
map <C-j> <Plug>(easymotion-j)
map <C-k> <Plug>(easymotion-k)

```

It seems to work in normal mode.

**Comment by zgqq** [comment]
I think it should work in insert mode.Simply because you don't need to know what mode you are in. A another reason is that if you want to move cursor other place you must exit insert mode,so increasing several keystroke.

**Comment by haya14busa** [comment]
Please use normal mode, visual mode or operator-pending mode.
I have no plan to support insert mode.

All builtin motions in Vim doesn't work in insert mode too.

**Comment by lfmet** [comment]
Use `<c-o` while in insert mode. This allows you to use one key from normal mode.
e.g. `<c-o>I`

**Comment by ywpkwon** [comment]
I just tried mapping `imap  <C-b>    <ESC><Plug>(easymotion-overwin-w)` expecting quitting from insert mode and run the function. It works when a buffer has been changed, but when a buffer has been changed in the insert mode, it shows an error message. Is this invalid operation?
