### ISSUE TITLE
Is there any way to query the locations of the matches using vimscript?

### ISSUE THREAD

**Issue by Chillee** [easymotion/vim-easymotion#331]
We've recently started adding neovim integration for [VSCodeVim](https://github.com/VSCodeVim/Vim), and one thing I've always hoped to do is to leverage vim's plugin ecosystem better.

I'd like to start with "officially" supporting the most popular plugins, and that would be easymotion. Is there any way to get the matches that are a result of an easymotion command?

We're using the neovim msgpack RPC api (https://neovim.io/doc/user/api.html)

**Comment by haya14busa** [comment]
I'm not exactly sure what you are talking about, but you can find algorithms here. https://github.com/haya14busa/vital-hit-a-hint/blob/master/autoload/vital/__latest__/HitAHint/Motion.vim

Do you mean you want some RPC service of easymotion?

**Comment by Chillee** [comment]
Yes. I would like some way of getting the matches of Easymotion through RPC. However, if there was some way of getting the results through a vimscript function call, that would suffice.

**Comment by haya14busa** [comment]
btw, the difficult part of Vim easymotion is

1. showing label by using conceal feature and replacing buffer text
2. interactively updating label with user type

I doubt it works through RPC, we need bi-directional support at least and there are some hacks for Vim buffer.

If you need only the algorithms, as I said above, you can find it https://github.com/haya14busa/vital-hit-a-hint/blob/master/autoload/vital/__latest__/HitAHint/Motion.vim.

Algorithms for choosing label is here.
https://github.com/haya14busa/vital-hit-a-hint/blob/master/autoload/vital/__latest__/HitAHint/Hint.vim

**Comment by Chillee** [comment]
@haya14busa Sorry, I am not very familiar with vimscript. Could you explain what I would need to do in order to be able to get the list of positions of the labels with the keybindings? And then choose the label?

I assume I would basically need to write a wrapper plugin?

Thank you for your time!

**Comment by Chillee** [comment]
This has become unnecessary: We are able to scrape highlights (including easymotion), so we can simply do ![](https://pbs.twimg.com/media/DN4WyfsW4AACb0j.jpg:large)
