### ISSUE TITLE
easymotion-bd-w doesn't work in Windows vim

### ISSUE THREAD

**Issue by amosbird** [easymotion/vim-easymotion#332]
It fails quietly. Here is a [screencast](https://la.wentropy.com/Oj29.webm)

**Comment by lfmet** [comment]
The link is broken `status: not found`.

**Comment by amosbird** [comment]
ah, it's out dated..   The issue is, evaluating `<Plug>(easymotion-bd-w` results in 
![](https://la.wentropy.com/fXKe.png)

**Comment by haya14busa** [comment]
Please paste more detailed errors. it might be there are trailing space at :map line.

**Comment by alexanderlperez** [comment]
>  it might be there are trailing space at :map line.

This was what was wrong with my config when trying to map `<Plug>(easymotion-w)` and it would just flash the targets and then fail with `Invalid Target`.

Hope this helps!
