### ISSUE TITLE
Customize characters used for hint 

### ISSUE THREAD

**Issue by dragonxlwang** [easymotion/vim-easymotion#335]
when easymotion is active, is there's a way to customize the character lists it used as hints?

I would love to remove "q" (or "q*" anything starts with a "q") out of the suggestion lists since 
I woud love to use that as a way to quit in the middle of "easy-motion".

Please let me know if this can be easily done.

Thanks,

**Comment by lfmet** [comment]
Read the docs, `EasyMotion_keys`. You can use `<Esc>` to quit easymotion.

**Comment by haya14busa** [comment]
:+1:
