### ISSUE TITLE
only default key map works

### ISSUE THREAD

**Issue by kimochg** [easymotion/vim-easymotion#336]
Here is my easy motion setting:
```
:map <localleader> <Plug>(easymotion-prefix)
:let g:EasyMotion_smartcase = 1
:nnoremap f <Plug>(easymotion-s)
:nnoremap s <Plug>(easymotion-overwin-f2)
:vnoremap f <Plug>(easymotion-s)
:noremap / <Plug>(easymotion-sn)
:onoremap / <Plug>(easymotion-tn)
```

Issue:
i.e. I press f , easy-motion just doesn't work.
but the default key mapping works fine. such as `<leader><leader>s`

my vim version: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 19 2017 09:53:00)
MacOS X (unix) version
Included patches: 1-567
Compiled by Homebrew
```

Any suggestion will be helpful !

**Comment by lfmet** [comment]
Don't use `nore`. Just `nmap f <Plug>(easymotion-s)` as it is in the documentation.
You don't need `map <localleader> <Plug>(easymotion-prefix)`, this is for the default mappings.

**Comment by haya14busa** [comment]
@ifmet thanks for the answer!

**Comment by kimochg** [comment]
@lfmet 
Sorry for late reply, thank you, it works now !
