### ISSUE TITLE
when i use s mode,p don't work.

### ISSUE THREAD

**Issue by ufwfqpdgv** [easymotion/vim-easymotion#337]
I set g to start s mode,so i can use like 'ga' to go a's pos,but when i input 'gp',it can't work,it become just p's function.because of this,when i want to go p's pos,i must input 'g' and then wait 1s,then input p,is it bug?

**Comment by lfmet** [comment]
Vim has default binds for `g`, you shoudn't remap it (alone). See `:help g`

**Comment by ufwfqpdgv** [comment]
Well,it seem can't be solved,so i change the s mode's start key to 'f',now it work well,cool...

**Comment by haya14busa** [comment]
You can use `<nowait>` but i don't recommend to overwrite `g` map.
```
:map <nowait> g <Plug>(easymotion-f)
```
