### ISSUE TITLE
n-character search highlight not show current cursor position

### ISSUE THREAD

**Issue by eromoe** [easymotion/vim-easymotion#338]
I set config 
```
" n-character search motion
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)

" These `n` & `N` mappings are options. You do not have to map `n` & `N` to EasyMotion.
" Without these mappings, `n` & `N` works fine.
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)
```

I find it is hard to figure out where I am while using `n` & `N`:
![image](https://user-images.githubusercontent.com/3938751/27579300-9b17cae4-5b59-11e7-879d-438198063557.png)

How to mark current cursor position with a different highlight?

**Comment by lfmet** [comment]
This isn't easymotion. It's the colorscheme you are using, see `:hi Search`.

**Comment by eromoe** [comment]
@lfmet Thank you to point that out .

`:hi Search` result:
![image](https://user-images.githubusercontent.com/3938751/28194186-270979ee-6875-11e7-8df9-21a5b31c396e.png)

I am using `color molokai`, not familiar with vim color.
Could you please give me a tip to fix this ? 

PS: I am on windows git-bash , I am afraid it is caused by OS...

**Comment by lfmet** [comment]
Actually, I was wrong. Apparently, the highlight doesn't work on neovim (only when you search with lowercase and a match starts with uppercase, probably a bug).

To solve your case, put this in your vimrc (see `:help easymotion-custom-hl` for more):
```vim
hi EasyMotionMoveHL ctermbg=magenta ctermfg=black guifg=#000000 guibg=#FF69B4
```

**Comment by eromoe** [comment]
![image](https://user-images.githubusercontent.com/3938751/28200273-a66a9592-689d-11e7-9e1b-884afde1b079.png)

Is this right ?  cursor does more visible in this background color.

**Comment by lfmet** [comment]
You can change `ctermbg` and `ctermfg` to anything between `0` and `256`. When you want to know more about a vim command try the docs (`:help hi`), they are really helpful.

Your visibility problem may be because your cursor shape isn't a block, you can search how to change it in the environment you are in.

**Comment by haya14busa** [comment]
Seems it's not a easymotion problem.

Thanks for the report and answer ! @lfmet  :+1: :+1: :+1:
