### ISSUE TITLE
Question: How to disable/override the C-j and C-k shortcuts?

### ISSUE THREAD

**Issue by fearphage** [easymotion/vim-easymotion#340]
I'm sure it's possible, but I can't figure out how to override the `C-j` and `C-k`.

I tried the following with no success:

```
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
```

I'm sure I'm missing something simple. Thanks in advance.

**Comment by lfmet** [comment]
These maps are not in the [default maps](https://github.com/easymotion/vim-easymotion/blob/master/doc/easymotion.txt#L97). Wrong repository? Try `:map <c-j>`.

**Comment by fearphage** [comment]
Thank you very much. `vim-move` was the culprit.
