### ISSUE TITLE
possible to define a deliminater?

### ISSUE THREAD

**Issue by justinyhuang** [easymotion/vim-easymotion#349]
it seems to me that easymotion tries to identify the jump locations by word, and it makes it hard to jump to the second 'N' in 'THIS_IS_A_NORMAL_NAME'. 
one thought would be to allow define the deliminaters, so that in the case above we can add '_' to the deliminater list and make the jump to the beginning of 'NAME' easier.
if there is already such a feature please ignore... #

**Comment by ELLIOTTCABLE** [comment]
Take a look at `:help iskeyword` and then `:help <Plug>(easymotion-iskeyword-w)` — you want to map one of the `-iskeyword-` versions, basically.

That said, I have a similar problem, because I much prefer the in-line mappings; and there is no `easymotion-iskeyword-wl`. @aya14busa?

**Comment by haya14busa** [comment]
Sorry for the late response and thank you for your answer.
I think it's closable. please reopen if not.

**Comment by justinyhuang** [comment]
thanks for all your help! it works for me now.
