### ISSUE TITLE
Target Keys All the Same  on Mac os 13.4

### ISSUE THREAD

**Issue by 92hackers** [easymotion/vim-easymotion#395]
when i search keys, all target keys the same one:
![vim-easymotion-bug](https://user-images.githubusercontent.com/5372618/51972300-0b13b700-24b6-11e9-8c54-9cda4ad42cba.png)

and when i enter the target key,  it always reminds me this: Invalid target: ... 

My OS is Macos 13.4
vim version: 8.0

**Comment by chenyuying** [comment]
Maybe you can update vim version to 8.1
check this
https://github.com/Homebrew/homebrew-core/issues/28077

brew update-reset
brew update
brew install vim
#and change your vim executive binary to /usr/local/bin/vim
/usr/local/bin/vim --version

**Comment by 92hackers** [comment]
Thanks, it works now。

**Comment by jyrodgers** [comment]
These steps fixed the same problem for neovim

brew update-reset
brew update
brew upgrade neovim
