### ISSUE TITLE
can't jump in many commands because of casing

### ISSUE THREAD

**Issue by eyalk5** [easymotion/vim-easymotion#399]
I have for example 
`nmap <Leader>w <Plug>(easymotion-overwin-w)`

when I try to go to a word, I enter this through \w and afterward, it regards what I typed as if it was uppercase. For example, if I wanted to go to nn, I type n and then it echos "invalid target N".

Of course capslock is off. It does work with 'search two chars'
I am with neovim 4.0.0

**Comment by ipsod** [comment]
I'm having this issue, too, with `nmap <return> <Plug>(easymotion-overwin-f)`.  The plugin won't work at all for me - always says `Invalid target: [capital version of whatever letter I pushed]`.

**Comment by ipsod** [comment]
I found that it was this config line that did it:
`let g:EasyMotion_use_upper = 1`

**Comment by haya14busa** [comment]
See `:h g:EasyMotion_use_upper`
