### ISSUE TITLE
How can I prevent easymotion from remapping ,,?

### ISSUE THREAD

**Issue by drericrobinson** [easymotion/vim-easymotion#438]
Hi,

I'm trying to use ,, for another mapping, but it keeps getting overwritten by easymotion. Is there any way to prevent this?

My current .vimrc includes this at the bottom of the file:
`:nunmap ,,`
`nnoremap ,, :w<cr>`

**Comment by iago-lito** [comment]
Does `:help easymotion-leader-key` help?

**Comment by drericrobinson** [comment]
Genius. Thanks.
