### ISSUE TITLE
Is anyone interested in this feature? first char word search

### ISSUE THREAD

**Issue by prizelk** [easymotion/vim-easymotion#448]
Hi, I have a modification in my easymotion.vim files that allows me to search for the first letter of all words. 

Initially, I used easymotion-s (single char bidirectional search), but since I really only use it to move to words (and not letters within a word), searching irrelevant chars often forced me to use 2 target keys. By using first char of words I pretty much never use 2 target keys which is amazing. This also goes with vim theme of object-based movement.

I want to make a pull request but Im not sure if people are interested so please let me know if this is a desired feature.

**Comment by C-Fergus** [comment]
Hi, I see that you closed this already but I would be interested in this future. I always know the first character of where I want to go and the extra target key is the bane of my existence.
